//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendApplicantSignUp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendApplicantSignUp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendApplicantSignUp", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string AcctNoLbl {
            get {
                return ResourceManager.GetString("AcctNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Limit Per Transaction.
        /// </summary>
        internal static string AmountLimitPerTransactionLbl {
            get {
                return ResourceManager.GetString("AmountLimitPerTransactionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Id.
        /// </summary>
        internal static string AppcIdLbl {
            get {
                return ResourceManager.GetString("AppcIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        internal static string CardNoLbl {
            get {
                return ResourceManager.GetString("CardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        internal static string DriverNameLbl {
            get {
                return ResourceManager.GetString("DriverNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emboss Name.
        /// </summary>
        internal static string EmbossNameLbl {
            get {
                return ResourceManager.GetString("EmbossNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Id.
        /// </summary>
        internal static string EntityIdLbl {
            get {
                return ResourceManager.GetString("EntityIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Check Flag.
        /// </summary>
        internal static string FuelCheckFlagLbl {
            get {
                return ResourceManager.GetString("FuelCheckFlagLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Indicator.
        /// </summary>
        internal static string FuelIndLbl {
            get {
                return ResourceManager.GetString("FuelIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Litre Per KM.
        /// </summary>
        internal static string FuelLitPerKMLbl {
            get {
                return ResourceManager.GetString("FuelLitPerKMLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Transaction Date.
        /// </summary>
        internal static string LastTxnDateLbl {
            get {
                return ResourceManager.GetString("LastTxnDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litre Limit Per Transaction.
        /// </summary>
        internal static string LitLimitLbl {
            get {
                return ResourceManager.GetString("LitLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litre Limit.
        /// </summary>
        internal static string LitreLimitLbl {
            get {
                return ResourceManager.GetString("LitreLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Check Flag.
        /// </summary>
        internal static string LocationCheckFlagLbl {
            get {
                return ResourceManager.GetString("LocationCheckFlagLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Indicator.
        /// </summary>
        internal static string LocationIndLbl {
            get {
                return ResourceManager.GetString("LocationIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Max Amount.
        /// </summary>
        internal static string LocationMaxAmtLbl {
            get {
                return ResourceManager.GetString("LocationMaxAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Max Counter.
        /// </summary>
        internal static string LocationMaxCntLbl {
            get {
                return ResourceManager.GetString("LocationMaxCntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Check Flag.
        /// </summary>
        internal static string LocCheckFlagLbl {
            get {
                return ResourceManager.GetString("LocCheckFlagLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Indicator.
        /// </summary>
        internal static string LocIndLbl {
            get {
                return ResourceManager.GetString("LocIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Max Amount.
        /// </summary>
        internal static string LocMaxAmtLbl {
            get {
                return ResourceManager.GetString("LocMaxAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Max Counter.
        /// </summary>
        internal static string LocMaxCntLbl {
            get {
                return ResourceManager.GetString("LocMaxCntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Maker.
        /// </summary>
        internal static string ManufacturerLbl {
            get {
                return ResourceManager.GetString("ManufacturerLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Reading Indicator.
        /// </summary>
        internal static string OdometerReadingIndLbl {
            get {
                return ResourceManager.GetString("OdometerReadingIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pin Tried Count.
        /// </summary>
        internal static string PinAttemptedLbl {
            get {
                return ResourceManager.GetString("PinAttemptedLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum PIN Tries.
        /// </summary>
        internal static string PINExceedCntLbl {
            get {
                return ResourceManager.GetString("PINExceedCntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Tried Update Date.
        /// </summary>
        internal static string PinTriedUpdDateLbl {
            get {
                return ResourceManager.GetString("PinTriedUpdDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Card.
        /// </summary>
        internal static string PrimaryCardLbl {
            get {
                return ResourceManager.GetString("PrimaryCardLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Alert Indicator.
        /// </summary>
        internal static string PushAlertIndLbl {
            get {
                return ResourceManager.GetString("PushAlertIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Fee.
        /// </summary>
        internal static string SelectedAnnualFeeDdl {
            get {
                return ResourceManager.GetString("SelectedAnnualFeeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        internal static string SelectedBranchCdDdl {
            get {
                return ResourceManager.GetString("SelectedBranchCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Media Type.
        /// </summary>
        internal static string SelectedCardMediaDdl {
            get {
                return ResourceManager.GetString("SelectedCardMediaDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        internal static string SelectedCardTypeDdl {
            get {
                return ResourceManager.GetString("SelectedCardTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Centre.
        /// </summary>
        internal static string SelectedCostCentreDdl {
            get {
                return ResourceManager.GetString("SelectedCostCentreDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        internal static string SelectedCurrentStatusDdl {
            get {
                return ResourceManager.GetString("SelectedCurrentStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        internal static string SelectedDeptCdDdl {
            get {
                return ResourceManager.GetString("SelectedDeptCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue Indicator.
        /// </summary>
        internal static string SelectedDialogueIndDdl {
            get {
                return ResourceManager.GetString("SelectedDialogueIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Code.
        /// </summary>
        internal static string SelectedDivisionCodeDdl {
            get {
                return ResourceManager.GetString("SelectedDivisionCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Fee.
        /// </summary>
        internal static string SelectedJoiningLbl {
            get {
                return ResourceManager.GetString("SelectedJoiningLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Indicator.
        /// </summary>
        internal static string SelectedPinIndDdl {
            get {
                return ResourceManager.GetString("SelectedPinIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Applicant Id.
        /// </summary>
        internal static string SelectedPrimaryApplicantIdDdl {
            get {
                return ResourceManager.GetString("SelectedPrimaryApplicantIdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string SelectedProductGroupDdl {
            get {
                return ResourceManager.GetString("SelectedProductGroupDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Utilization.
        /// </summary>
        internal static string SelectedProductUtilizationDdl {
            get {
                return ResourceManager.GetString("SelectedProductUtilizationDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKDS No.
        /// </summary>
        internal static string SelectedSKDSNoDdl {
            get {
                return ResourceManager.GetString("SelectedSKDSNoDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        internal static string SelectedVehicleModelDdl {
            get {
                return ResourceManager.GetString("SelectedVehicleModelDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKDS Indicator.
        /// </summary>
        internal static string SKDSIndLbl {
            get {
                return ResourceManager.GetString("SKDSIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKDS Quota.
        /// </summary>
        internal static string SKDSQuotaLbl {
            get {
                return ResourceManager.GetString("SKDSQuotaLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Limit.
        /// </summary>
        internal static string TxnLimitLbl {
            get {
                return ResourceManager.GetString("TxnLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string UserIdLbl {
            get {
                return ResourceManager.GetString("UserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Registration No.
        /// </summary>
        internal static string VehRegNoLbl {
            get {
                return ResourceManager.GetString("VehRegNoLbl", resourceCulture);
            }
        }
    }
}
