//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendAcctSignUp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendAcctSignUp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendAcctSignUp", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acct No.
        /// </summary>
        internal static string AcctNo1Lbl {
            get {
                return ResourceManager.GetString("AcctNo1Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string AcctNoLbl {
            get {
                return ResourceManager.GetString("AcctNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string Address1Lbl {
            get {
                return ResourceManager.GetString("Address1Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Address2Lbl {
            get {
                return ResourceManager.GetString("Address2Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        internal static string Address3Lbl {
            get {
                return ResourceManager.GetString("Address3Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 4.
        /// </summary>
        internal static string Address4Lbl {
            get {
                return ResourceManager.GetString("Address4Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 5.
        /// </summary>
        internal static string Address5Lbl {
            get {
                return ResourceManager.GetString("Address5Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressLbl {
            get {
                return ResourceManager.GetString("AddressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Limit.
        /// </summary>
        internal static string AmtLimitLbl {
            get {
                return ResourceManager.GetString("AmtLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Id.
        /// </summary>
        internal static string AppcCardId {
            get {
                return ResourceManager.GetString("AppcCardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Id.
        /// </summary>
        internal static string AppcIdLbl {
            get {
                return ResourceManager.GetString("AppcIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Id.
        /// </summary>
        internal static string ApplicationIdLbl {
            get {
                return ResourceManager.GetString("ApplicationIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Ref.
        /// </summary>
        internal static string ApplicationRefLbl {
            get {
                return ResourceManager.GetString("ApplicationRefLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        internal static string ApprovedDateLbl {
            get {
                return ResourceManager.GetString("ApprovedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code.
        /// </summary>
        internal static string AppvCdLbl {
            get {
                return ResourceManager.GetString("AppvCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appl ID.
        /// </summary>
        internal static string AprId {
            get {
                return ResourceManager.GetString("AprId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Date.
        /// </summary>
        internal static string AuthDateLbl {
            get {
                return ResourceManager.GetString("AuthDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authoriser Name.
        /// </summary>
        internal static string AuthNameLbl {
            get {
                return ResourceManager.GetString("AuthNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Signatory.
        /// </summary>
        internal static string AuthSignatoryLbl {
            get {
                return ResourceManager.GetString("AuthSignatoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Date.
        /// </summary>
        internal static string BlockedDateLbl {
            get {
                return ResourceManager.GetString("BlockedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Expiry.
        /// </summary>
        internal static string CardExpiryLbl {
            get {
                return ResourceManager.GetString("CardExpiryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        internal static string CardNoLbl {
            get {
                return ResourceManager.GetString("CardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumberLbl {
            get {
                return ResourceManager.GetString("CardNumberLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Terminated.
        /// </summary>
        internal static string CardTerminatedLbl {
            get {
                return ResourceManager.GetString("CardTerminatedLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ChequeAmtLbl {
            get {
                return ResourceManager.GetString("ChequeAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No.
        /// </summary>
        internal static string ChequeNoLbl {
            get {
                return ResourceManager.GetString("ChequeNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityLbl {
            get {
                return ResourceManager.GetString("CityLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Count.
        /// </summary>
        internal static string CntrLimitLbl {
            get {
                return ResourceManager.GetString("CntrLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Emboss Name.
        /// </summary>
        internal static string CompanyEmbNameLbl {
            get {
                return ResourceManager.GetString("CompanyEmbNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyLegalNameLbl {
            get {
                return ResourceManager.GetString("CompanyLegalNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name / Individual Name.
        /// </summary>
        internal static string CompanyNameLbl {
            get {
                return ResourceManager.GetString("CompanyNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration Date.
        /// </summary>
        internal static string CompanyRegnDateLbl {
            get {
                return ResourceManager.GetString("CompanyRegnDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration Name.
        /// </summary>
        internal static string CompanyRegnNameLbl {
            get {
                return ResourceManager.GetString("CompanyRegnNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration No. / IC No..
        /// </summary>
        internal static string CompanyRegnNoLbl {
            get {
                return ResourceManager.GetString("CompanyRegnNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string ContactNameLbl {
            get {
                return ResourceManager.GetString("ContactNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        internal static string ContactNoLbl {
            get {
                return ResourceManager.GetString("ContactNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string ContactPersonLbl {
            get {
                return ResourceManager.GetString("ContactPersonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Name.
        /// </summary>
        internal static string CorporateNameLbl {
            get {
                return ResourceManager.GetString("CorporateNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Centre.
        /// </summary>
        internal static string CostCentreLbl {
            get {
                return ResourceManager.GetString("CostCentreLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDateLbl {
            get {
                return ResourceManager.GetString("CreationDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit.
        /// </summary>
        internal static string CreditLimitLbl {
            get {
                return ResourceManager.GetString("CreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle No &amp; Date.
        /// </summary>
        internal static string CycleNonDateLbl {
            get {
                return ResourceManager.GetString("CycleNonDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Limit.
        /// </summary>
        internal static string DdlVelocityLimitLbl {
            get {
                return ResourceManager.GetString("DdlVelocityLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Litre.
        /// </summary>
        internal static string DdlVelocityLitreLbl {
            get {
                return ResourceManager.GetString("DdlVelocityLitreLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descp.
        /// </summary>
        internal static string DescpLbl {
            get {
                return ResourceManager.GetString("DescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descpription.
        /// </summary>
        internal static string DescpriptionLbl {
            get {
                return ResourceManager.GetString("DescpriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string DistrictLbl {
            get {
                return ResourceManager.GetString("DistrictLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Order No..
        /// </summary>
        internal static string DriverCdLbl {
            get {
                return ResourceManager.GetString("DriverCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        internal static string DriverNameLbl {
            get {
                return ResourceManager.GetString("DriverNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string DueDateLbl {
            get {
                return ResourceManager.GetString("DueDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddressLbl {
            get {
                return ResourceManager.GetString("EmailAddressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddrLbl {
            get {
                return ResourceManager.GetString("EmailAddrLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emboss Name.
        /// </summary>
        internal static string EmbossNameLbl {
            get {
                return ResourceManager.GetString("EmbossNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Id.
        /// </summary>
        internal static string EntityIdLbl {
            get {
                return ResourceManager.GetString("EntityIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Litre/ per KM.
        /// </summary>
        internal static string FuelLitreLbl {
            get {
                return ResourceManager.GetString("FuelLitreLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullNameLbl {
            get {
                return ResourceManager.GetString("FullNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IDLbl {
            get {
                return ResourceManager.GetString("IDLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer Cd.
        /// </summary>
        internal static string InsurerCdLbl {
            get {
                return ResourceManager.GetString("InsurerCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Printing Indicator.
        /// </summary>
        internal static string InvoiceBillingIndicatorLbl {
            get {
                return ResourceManager.GetString("InvoiceBillingIndicatorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Invoice Indicator.
        /// </summary>
        internal static string InvoiceIndCopyLbl {
            get {
                return ResourceManager.GetString("InvoiceIndCopyLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Transaction Date.
        /// </summary>
        internal static string LastTransactionDateLbl {
            get {
                return ResourceManager.GetString("LastTransactionDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        internal static string lastUpdateDateLbl {
            get {
                return ResourceManager.GetString("lastUpdateDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Upd Date.
        /// </summary>
        internal static string LastUpdDateLbl {
            get {
                return ResourceManager.GetString("LastUpdDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Indicator.
        /// </summary>
        internal static string LocIndLbl {
            get {
                return ResourceManager.GetString("LocIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Card No.
        /// </summary>
        internal static string LoyaltyCardNoLbl {
            get {
                return ResourceManager.GetString("LoyaltyCardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Contact No.
        /// </summary>
        internal static string LoyaltyContactNoLbl {
            get {
                return ResourceManager.GetString("LoyaltyContactNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Business.
        /// </summary>
        internal static string LoyaltyeBusnLbl {
            get {
                return ResourceManager.GetString("LoyaltyeBusnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Full Name.
        /// </summary>
        internal static string LoyaltyFullNameLbl {
            get {
                return ResourceManager.GetString("LoyaltyFullNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Ic No.
        /// </summary>
        internal static string LoyaltyIcNoLbl {
            get {
                return ResourceManager.GetString("LoyaltyIcNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Mailing Indicator.
        /// </summary>
        internal static string MainMailingIndLbl {
            get {
                return ResourceManager.GetString("MainMailingIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Count Limit.
        /// </summary>
        internal static string MaxCountLimitLbl {
            get {
                return ResourceManager.GetString("MaxCountLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Since.
        /// </summary>
        internal static string MemberSinceLbl {
            get {
                return ResourceManager.GetString("MemberSinceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string MobileNoLbl {
            get {
                return ResourceManager.GetString("MobileNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Indicator.
        /// </summary>
        internal static string OdometerIndicatorLbl {
            get {
                return ResourceManager.GetString("OdometerIndicatorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Odometer Reading.
        /// </summary>
        internal static string OdoMeterReadingLbl {
            get {
                return ResourceManager.GetString("OdoMeterReadingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Update.
        /// </summary>
        internal static string OdoMeterUpdateLbl {
            get {
                return ResourceManager.GetString("OdoMeterUpdateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Fax.
        /// </summary>
        internal static string OfficeFaxLbl {
            get {
                return ResourceManager.GetString("OfficeFaxLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Phone.
        /// </summary>
        internal static string OfficePhoneLbl {
            get {
                return ResourceManager.GetString("OfficePhoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev CardNo.
        /// </summary>
        internal static string OldCardNoLbl {
            get {
                return ResourceManager.GetString("OldCardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person In Charge.
        /// </summary>
        internal static string PersonInChargeLbl {
            get {
                return ResourceManager.GetString("PersonInChargeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Failed Attempted.
        /// </summary>
        internal static string PINAttemptedLbl {
            get {
                return ResourceManager.GetString("PINAttemptedLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max PIN Tries.
        /// </summary>
        internal static string PINExceedCntLbl {
            get {
                return ResourceManager.GetString("PINExceedCntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string PinLbl {
            get {
                return ResourceManager.GetString("PinLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Offset.
        /// </summary>
        internal static string PINOffsetLbl {
            get {
                return ResourceManager.GetString("PINOffsetLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Amount.
        /// </summary>
        internal static string PolicyAmtLbl {
            get {
                return ResourceManager.GetString("PolicyAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Expiry Date.
        /// </summary>
        internal static string PolicyExpDateLbl {
            get {
                return ResourceManager.GetString("PolicyExpDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy No.
        /// </summary>
        internal static string PolicyNoLbl {
            get {
                return ResourceManager.GetString("PolicyNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string PositionLbl {
            get {
                return ResourceManager.GetString("PositionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCodeLbl {
            get {
                return ResourceManager.GetString("PostalCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Amount.
        /// </summary>
        internal static string PremiumAmtLbl {
            get {
                return ResourceManager.GetString("PremiumAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Card.
        /// </summary>
        internal static string PrimaryCardLbl {
            get {
                return ResourceManager.GetString("PrimaryCardLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PW.
        /// </summary>
        internal static string PVVLbl {
            get {
                return ResourceManager.GetString("PVVLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Indicator.
        /// </summary>
        internal static string PymtIndLbl {
            get {
                return ResourceManager.GetString("PymtIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Date.
        /// </summary>
        internal static string RecallDateLbl {
            get {
                return ResourceManager.GetString("RecallDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Date.
        /// </summary>
        internal static string ReceiveDateLbl {
            get {
                return ResourceManager.GetString("ReceiveDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Code.
        /// </summary>
        internal static string RefCdLbl {
            get {
                return ResourceManager.GetString("RefCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Key.
        /// </summary>
        internal static string RefKeyLbl {
            get {
                return ResourceManager.GetString("RefKeyLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefNo.
        /// </summary>
        internal static string RefNoLbl {
            get {
                return ResourceManager.GetString("RefNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Date.
        /// </summary>
        internal static string RejectedDateLbl {
            get {
                return ResourceManager.GetString("RejectedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string RemarksLbl {
            get {
                return ResourceManager.GetString("RemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Period.
        /// </summary>
        internal static string RenewalPeriodLbl {
            get {
                return ResourceManager.GetString("RenewalPeriodLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request By.
        /// </summary>
        internal static string RequestByLbl {
            get {
                return ResourceManager.GetString("RequestByLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Value.
        /// </summary>
        internal static string RequestValueLbl {
            get {
                return ResourceManager.GetString("RequestValueLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Tax Amount.
        /// </summary>
        internal static string RoadTaxAmtLbl {
            get {
                return ResourceManager.GetString("RoadTaxAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Tax Expiry Date.
        /// </summary>
        internal static string RoadTaxExpDateLbl {
            get {
                return ResourceManager.GetString("RoadTaxExpDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP No.
        /// </summary>
        internal static string SapNoLbl {
            get {
                return ResourceManager.GetString("SapNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Amount.
        /// </summary>
        internal static string SecurityAmtLbl {
            get {
                return ResourceManager.GetString("SecurityAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        internal static string SelectedAddrTypeDdl {
            get {
                return ResourceManager.GetString("SelectedAddrTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual &amp; Fee.
        /// </summary>
        internal static string SelectedAnnualFeeDdl {
            get {
                return ResourceManager.GetString("SelectedAnnualFeeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Type.
        /// </summary>
        internal static string SelectedBillingTypeDdl {
            get {
                return ResourceManager.GetString("SelectedBillingTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        internal static string SelectedBranchCdDdl {
            get {
                return ResourceManager.GetString("SelectedBranchCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category.
        /// </summary>
        internal static string SelectedBusinessCategoryDdl {
            get {
                return ResourceManager.GetString("SelectedBusinessCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Media Type.
        /// </summary>
        internal static string SelectedCardMediaDdl {
            get {
                return ResourceManager.GetString("SelectedCardMediaDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Status.
        /// </summary>
        internal static string SelectedCardStsLbl {
            get {
                return ResourceManager.GetString("SelectedCardStsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        internal static string SelectedCardTypeDdl {
            get {
                return ResourceManager.GetString("SelectedCardTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Class.
        /// </summary>
        internal static string SelectedClientClassDdl {
            get {
                return ResourceManager.GetString("SelectedClientClassDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Type.
        /// </summary>
        internal static string SelectedClientTypeDdl {
            get {
                return ResourceManager.GetString("SelectedClientTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        internal static string selectedCompanyTypeDdl {
            get {
                return ResourceManager.GetString("selectedCompanyTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        internal static string SelectedContactTypeDdl {
            get {
                return ResourceManager.GetString("SelectedContactTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corp Cd.
        /// </summary>
        internal static string SelectedCorpCdDdl {
            get {
                return ResourceManager.GetString("SelectedCorpCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Account.
        /// </summary>
        internal static string SelectedCorporateAcctDdl {
            get {
                return ResourceManager.GetString("SelectedCorporateAcctDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Centre.
        /// </summary>
        internal static string SelectedCostCentreDdl {
            get {
                return ResourceManager.GetString("SelectedCostCentreDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string SelectedCountryDdl {
            get {
                return ResourceManager.GetString("SelectedCountryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Type.
        /// </summary>
        internal static string SelectedCtrlTypeDdl {
            get {
                return ResourceManager.GetString("SelectedCtrlTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        internal static string SelectedCurrentStatusDdl {
            get {
                return ResourceManager.GetString("SelectedCurrentStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle No.
        /// </summary>
        internal static string SelectedCycleNoDdl {
            get {
                return ResourceManager.GetString("SelectedCycleNoDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        internal static string SelectedDeptCdDdl {
            get {
                return ResourceManager.GetString("SelectedDeptCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string SelectedDesignationDdl {
            get {
                return ResourceManager.GetString("SelectedDesignationDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue Indicator.
        /// </summary>
        internal static string SelectedDialogueIndDdl {
            get {
                return ResourceManager.GetString("SelectedDialogueIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Code.
        /// </summary>
        internal static string SelectedDivisionCodeDdl {
            get {
                return ResourceManager.GetString("SelectedDivisionCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Check Flag.
        /// </summary>
        internal static string SelectedFuelCheckFlagChk {
            get {
                return ResourceManager.GetString("SelectedFuelCheckFlagChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Indicator.
        /// </summary>
        internal static string SelectedFuelIndDdl {
            get {
                return ResourceManager.GetString("SelectedFuelIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Preference.
        /// </summary>
        internal static string SelectedInvoicePrefDdl {
            get {
                return ResourceManager.GetString("SelectedInvoicePrefDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Fee.
        /// </summary>
        internal static string SelectedJonFeeDdl {
            get {
                return ResourceManager.GetString("SelectedJonFeeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SelectedLangIdDdl {
            get {
                return ResourceManager.GetString("SelectedLangIdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Check Flag.
        /// </summary>
        internal static string SelectedLocCheckFlagChk {
            get {
                return ResourceManager.GetString("SelectedLocCheckFlagChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature Of Business.
        /// </summary>
        internal static string SelectedNatureOfBusinessDdl {
            get {
                return ResourceManager.GetString("SelectedNatureOfBusinessDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string SelectedOccupationDdl {
            get {
                return ResourceManager.GetString("SelectedOccupationDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string SelectedOwnerDdl {
            get {
                return ResourceManager.GetString("SelectedOwnerDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        internal static string SelectedPaymentModeDdl {
            get {
                return ResourceManager.GetString("SelectedPaymentModeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Indicator.
        /// </summary>
        internal static string SelectedPINIndDdl {
            get {
                return ResourceManager.GetString("SelectedPINIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Type.
        /// </summary>
        internal static string selectedPlasticTypeDdl {
            get {
                return ResourceManager.GetString("selectedPlasticTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string SelectedPriorityDdl {
            get {
                return ResourceManager.GetString("SelectedPriorityDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string SelectedProdCdDdl {
            get {
                return ResourceManager.GetString("SelectedProdCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string SelectedProductGroupDdl {
            get {
                return ResourceManager.GetString("SelectedProductGroupDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string SelectedProductUtilizationDdl {
            get {
                return ResourceManager.GetString("SelectedProductUtilizationDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Alert Indicator.
        /// </summary>
        internal static string SelectedPushAlertIndDdl {
            get {
                return ResourceManager.GetString("SelectedPushAlertIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        internal static string SelectedReasonCdDdl {
            get {
                return ResourceManager.GetString("SelectedReasonCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SelectedReasonCodeDdl {
            get {
                return ResourceManager.GetString("SelectedReasonCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string SelectedRegionDdl {
            get {
                return ResourceManager.GetString("SelectedRegionDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Indicator.
        /// </summary>
        internal static string SelectedRenewalIndDdl {
            get {
                return ResourceManager.GetString("SelectedRenewalIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKDS Indicator.
        /// </summary>
        internal static string SelectedSKDSIndChk {
            get {
                return ResourceManager.GetString("SelectedSKDSIndChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy No.
        /// </summary>
        internal static string SelectedSKDSNoDdl {
            get {
                return ResourceManager.GetString("SelectedSKDSNoDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string SelectedstateDdl {
            get {
                return ResourceManager.GetString("SelectedstateDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Type.
        /// </summary>
        internal static string SelectedStatementTypeDdl {
            get {
                return ResourceManager.GetString("SelectedStatementTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SelectedStatusDdl {
            get {
                return ResourceManager.GetString("SelectedStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Status.
        /// </summary>
        internal static string SelectedStsDdl {
            get {
                return ResourceManager.GetString("SelectedStsDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string SelectedTaskNoDdl {
            get {
                return ResourceManager.GetString("SelectedTaskNoDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Category.
        /// </summary>
        internal static string SelectedTaxCategoryDdl {
            get {
                return ResourceManager.GetString("SelectedTaxCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Type.
        /// </summary>
        internal static string SelectedTxnCdDdl {
            get {
                return ResourceManager.GetString("SelectedTxnCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Code.
        /// </summary>
        internal static string SelectedTxnCodeDdl {
            get {
                return ResourceManager.GetString("SelectedTxnCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Color.
        /// </summary>
        internal static string SelectedVehColorDdl {
            get {
                return ResourceManager.GetString("SelectedVehColorDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        internal static string SelectedVehicleModelDdl {
            get {
                return ResourceManager.GetString("SelectedVehicleModelDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Maker.
        /// </summary>
        internal static string SelectedVehMakerDdl {
            get {
                return ResourceManager.GetString("SelectedVehMakerDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        internal static string SelectedVehModelDdl {
            get {
                return ResourceManager.GetString("SelectedVehModelDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        internal static string SelectedVehTypeDdl {
            get {
                return ResourceManager.GetString("SelectedVehTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Year.
        /// </summary>
        internal static string SelectedVehYrDdl {
            get {
                return ResourceManager.GetString("SelectedVehYrDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Limit Type.
        /// </summary>
        internal static string SelectedVelocityIndDdl {
            get {
                return ResourceManager.GetString("SelectedVelocityIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        internal static string ShortNameLbl {
            get {
                return ResourceManager.GetString("ShortNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKDS Indicator.
        /// </summary>
        internal static string SkdsIndLbl {
            get {
                return ResourceManager.GetString("SkdsIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKDS Quota.
        /// </summary>
        internal static string SkdsQuotaLbl {
            get {
                return ResourceManager.GetString("SkdsQuotaLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string SourceCodeLbl {
            get {
                return ResourceManager.GetString("SourceCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Reference No.
        /// </summary>
        internal static string SourceRefNoLbl {
            get {
                return ResourceManager.GetString("SourceRefNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent Counter.
        /// </summary>
        internal static string SpentCntLbl {
            get {
                return ResourceManager.GetString("SpentCntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent Amount.
        /// </summary>
        internal static string SpentLimitLbl {
            get {
                return ResourceManager.GetString("SpentLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent Litre.
        /// </summary>
        internal static string SpentLitreLbl {
            get {
                return ResourceManager.GetString("SpentLitreLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Descp.
        /// </summary>
        internal static string TaskDescpLbl {
            get {
                return ResourceManager.GetString("TaskDescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated Date.
        /// </summary>
        internal static string TerminatedDateLbl {
            get {
                return ResourceManager.GetString("TerminatedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Amount.
        /// </summary>
        internal static string TotAmntLbl {
            get {
                return ResourceManager.GetString("TotAmntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Amount Limit.
        /// </summary>
        internal static string TransAmtLimitLbl {
            get {
                return ResourceManager.GetString("TransAmtLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Litre Limit.
        /// </summary>
        internal static string TransLitreLimitLbl {
            get {
                return ResourceManager.GetString("TransLitreLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Date.
        /// </summary>
        internal static string TxnDateLbl {
            get {
                return ResourceManager.GetString("TxnDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string UserIdLbl {
            get {
                return ResourceManager.GetString("UserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Analysis Report.
        /// </summary>
        internal static string VehiclePerformanceReportIndLbl {
            get {
                return ResourceManager.GetString("VehiclePerformanceReportIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle performance report.
        /// </summary>
        internal static string VehiclePerformanceReportLbl {
            get {
                return ResourceManager.GetString("VehiclePerformanceReportLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Service Date.
        /// </summary>
        internal static string VehicleServiceDateLbl {
            get {
                return ResourceManager.GetString("VehicleServiceDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Registration Date.
        /// </summary>
        internal static string VehRegDateLbl {
            get {
                return ResourceManager.GetString("VehRegDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Registration No.
        /// </summary>
        internal static string VehRegNoLbl {
            get {
                return ResourceManager.GetString("VehRegNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Registration No.
        /// </summary>
        internal static string VehRegtNoLbl {
            get {
                return ResourceManager.GetString("VehRegtNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Counter.
        /// </summary>
        internal static string VelocityCounterLbl {
            get {
                return ResourceManager.GetString("VelocityCounterLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Amount.
        /// </summary>
        internal static string VelocityLimitLbl {
            get {
                return ResourceManager.GetString("VelocityLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Litre.
        /// </summary>
        internal static string VelocityLitreLbl {
            get {
                return ResourceManager.GetString("VelocityLitreLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string WebsiteLbl {
            get {
                return ResourceManager.GetString("WebsiteLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding Tax Indicator.
        /// </summary>
        internal static string WithholdingTaxIndLbl {
            get {
                return ResourceManager.GetString("WithholdingTaxIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Code.
        /// </summary>
        internal static string WorkflowcdLbl {
            get {
                return ResourceManager.GetString("WorkflowcdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev Card No..
        /// </summary>
        internal static string XrefCardNoLbl {
            get {
                return ResourceManager.GetString("XrefCardNoLbl", resourceCulture);
            }
        }
    }
}
