//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendCardHolder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendCardHolder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendCardHolder", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string AccNoLbl {
            get {
                return ResourceManager.GetString("AccNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Identity No.
        /// </summary>
        internal static string AltIdNoLbl {
            get {
                return ResourceManager.GetString("AltIdNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Income.
        /// </summary>
        internal static string AnnualIncomeLbl {
            get {
                return ResourceManager.GetString("AnnualIncomeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Id.
        /// </summary>
        internal static string AppcIdLbl {
            get {
                return ResourceManager.GetString("AppcIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        internal static string BusnLocationLbl {
            get {
                return ResourceManager.GetString("BusnLocationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        internal static string CardNoLbl {
            get {
                return ResourceManager.GetString("CardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDateLbl {
            get {
                return ResourceManager.GetString("CreationDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBA Name.
        /// </summary>
        internal static string DBANameLbl {
            get {
                return ResourceManager.GetString("DBANameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescpLbl {
            get {
                return ResourceManager.GetString("DescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        internal static string DOBLbl {
            get {
                return ResourceManager.GetString("DOBLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving License.
        /// </summary>
        internal static string DrivingLicenseLbl {
            get {
                return ResourceManager.GetString("DrivingLicenseLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Id.
        /// </summary>
        internal static string EntityIdLbl {
            get {
                return ResourceManager.GetString("EntityIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string ExpiryDateLbl {
            get {
                return ResourceManager.GetString("ExpiryDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstNameLbl {
            get {
                return ResourceManager.GetString("FirstNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity No.
        /// </summary>
        internal static string IdNoLbl {
            get {
                return ResourceManager.GetString("IdNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastNameLbl {
            get {
                return ResourceManager.GetString("LastNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merch Acct No.
        /// </summary>
        internal static string MerchAcctNoLbl {
            get {
                return ResourceManager.GetString("MerchAcctNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card Expiry Date.
        /// </summary>
        internal static string NewCardExpiryDateLbl {
            get {
                return ResourceManager.GetString("NewCardExpiryDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card No.
        /// </summary>
        internal static string NewCardNoLbl {
            get {
                return ResourceManager.GetString("NewCardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Id.
        /// </summary>
        internal static string RefIdLbl {
            get {
                return ResourceManager.GetString("RefIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string RemarksLbl {
            get {
                return ResourceManager.GetString("RemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Identity Type.
        /// </summary>
        internal static string SelectedAltIdTypeDdl {
            get {
                return ResourceManager.GetString("SelectedAltIdTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string SelectedBusnLocationsDdl {
            get {
                return ResourceManager.GetString("SelectedBusnLocationsDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Media Type.
        /// </summary>
        internal static string SelectedCardMediaTypeDdl {
            get {
                return ResourceManager.GetString("SelectedCardMediaTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status To.
        /// </summary>
        internal static string SelectedChangeStatusToDdl {
            get {
                return ResourceManager.GetString("SelectedChangeStatusToDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Status.
        /// </summary>
        internal static string SelectedChangetoStatusDdl {
            get {
                return ResourceManager.GetString("SelectedChangetoStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        internal static string SelectedCurrentStatusDdl {
            get {
                return ResourceManager.GetString("SelectedCurrentStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string SelectedDeptIdDdl {
            get {
                return ResourceManager.GetString("SelectedDeptIdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Fee.
        /// </summary>
        internal static string SelectedFeeCdDdl {
            get {
                return ResourceManager.GetString("SelectedFeeCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string SelectedgenderDdl {
            get {
                return ResourceManager.GetString("SelectedgenderDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity No. Type.
        /// </summary>
        internal static string SelectedIdTypeDdl {
            get {
                return ResourceManager.GetString("SelectedIdTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string SelectedOccupationDdl {
            get {
                return ResourceManager.GetString("SelectedOccupationDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        internal static string SelectedReasonCodeDdl {
            get {
                return ResourceManager.GetString("SelectedReasonCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type.
        /// </summary>
        internal static string SelectedRefTypeLbl {
            get {
                return ResourceManager.GetString("SelectedRefTypeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string SelectedStatesDdl {
            get {
                return ResourceManager.GetString("SelectedStatesDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SelectedTitleDdl {
            get {
                return ResourceManager.GetString("SelectedTitleDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ID.
        /// </summary>
        internal static string SiteIdLbl {
            get {
                return ResourceManager.GetString("SiteIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated Date.
        /// </summary>
        internal static string TerminatedDateLbl {
            get {
                return ResourceManager.GetString("TerminatedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string UserIdLbl {
            get {
                return ResourceManager.GetString("UserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xReference Id.
        /// </summary>
        internal static string XReferenceIDLbl {
            get {
                return ResourceManager.GetString("XReferenceIDLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Card No.
        /// </summary>
        internal static string XReferenceNoLbl {
            get {
                return ResourceManager.GetString("XReferenceNoLbl", resourceCulture);
            }
        }
    }
}
