//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendGlobalVariable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendGlobalVariable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendGlobalVariable", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply All Indicator.
        /// </summary>
        internal static string ApplyAllIndLbl {
            get {
                return ResourceManager.GetString("ApplyAllIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Code.
        /// </summary>
        internal static string CityCodeLbl {
            get {
                return ResourceManager.GetString("CityCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        internal static string CityNameLbl {
            get {
                return ResourceManager.GetString("CityNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Name.
        /// </summary>
        internal static string CompanyNameLbl {
            get {
                return ResourceManager.GetString("CompanyNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Indicator.
        /// </summary>
        internal static string DefaultIndLbl {
            get {
                return ResourceManager.GetString("DefaultIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        internal static string DescpLbl {
            get {
                return ResourceManager.GetString("DescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Description.
        /// </summary>
        internal static string DetailedDescpLbl {
            get {
                return ResourceManager.GetString("DetailedDescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        internal static string EffectiveFromLbl {
            get {
                return ResourceManager.GetString("EffectiveFromLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id.
        /// </summary>
        internal static string EventIdLbl {
            get {
                return ResourceManager.GetString("EventIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciept ID.
        /// </summary>
        internal static string EventRcptIdLbl {
            get {
                return ResourceManager.GetString("EventRcptIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id.
        /// </summary>
        internal static string EventScheduleIdLbl {
            get {
                return ResourceManager.GetString("EventScheduleIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type ID.
        /// </summary>
        internal static string EventTypeIdLbl {
            get {
                return ResourceManager.GetString("EventTypeIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string ExpiryDateLbl {
            get {
                return ResourceManager.GetString("ExpiryDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Occur.
        /// </summary>
        internal static string MaxOccurLbl {
            get {
                return ResourceManager.GetString("MaxOccurLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Code.
        /// </summary>
        internal static string ParameterCodeLbl {
            get {
                return ResourceManager.GetString("ParameterCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Description.
        /// </summary>
        internal static string ParameterDescpLbl {
            get {
                return ResourceManager.GetString("ParameterDescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Id.
        /// </summary>
        internal static string PlanIdLbl {
            get {
                return ResourceManager.GetString("PlanIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProdDescpLbl {
            get {
                return ResourceManager.GetString("ProdDescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string ProductCodeLbl {
            get {
                return ResourceManager.GetString("ProductCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Key.
        /// </summary>
        internal static string RefKeyLbl {
            get {
                return ResourceManager.GetString("RefKeyLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Plan.
        /// </summary>
        internal static string SelectedBillingPlanDdl {
            get {
                return ResourceManager.GetString("SelectedBillingPlanDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        internal static string SelectedEventTypeDdl {
            get {
                return ResourceManager.GetString("SelectedEventTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string SelectedFrequencyDdl {
            get {
                return ResourceManager.GetString("SelectedFrequencyDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SelectedlanguageDdl {
            get {
                return ResourceManager.GetString("SelectedlanguageDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string SelectedOwnerDdl {
            get {
                return ResourceManager.GetString("SelectedOwnerDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string SelectedPriorityDdl {
            get {
                return ResourceManager.GetString("SelectedPriorityDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        internal static string SelectedProductCategoryDdl {
            get {
                return ResourceManager.GetString("SelectedProductCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string SelectedProductGroupDdl {
            get {
                return ResourceManager.GetString("SelectedProductGroupDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string SelectedProductTypeDdl {
            get {
                return ResourceManager.GetString("SelectedProductTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref To.
        /// </summary>
        internal static string SelectedRefToDdl {
            get {
                return ResourceManager.GetString("SelectedRefToDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string SelectedScopeDdl {
            get {
                return ResourceManager.GetString("SelectedScopeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string SelectedTypeDdl {
            get {
                return ResourceManager.GetString("SelectedTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Indicator.
        /// </summary>
        internal static string SeletedEventIndDdl {
            get {
                return ResourceManager.GetString("SeletedEventIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        internal static string ShortDescpLbl {
            get {
                return ResourceManager.GetString("ShortDescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Code.
        /// </summary>
        internal static string StateCodeLbl {
            get {
                return ResourceManager.GetString("StateCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        internal static string StateNameLbl {
            get {
                return ResourceManager.GetString("StateNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time(s).
        /// </summary>
        internal static string TimesLbl {
            get {
                return ResourceManager.GetString("TimesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeDescLbl {
            get {
                return ResourceManager.GetString("TypeDescLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        internal static string TypeLbl {
            get {
                return ResourceManager.GetString("TypeLbl", resourceCulture);
            }
        }
    }
}
