//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendMechSignUp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendMechSignUp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendMechSignUp", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string AcctNoLbl {
            get {
                return ResourceManager.GetString("AcctNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        internal static string Address1Lbl {
            get {
                return ResourceManager.GetString("Address1Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        internal static string Address2Lbl {
            get {
                return ResourceManager.GetString("Address2Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address3.
        /// </summary>
        internal static string Address3Lbl {
            get {
                return ResourceManager.GetString("Address3Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Date.
        /// </summary>
        internal static string AgreementDateLbl {
            get {
                return ResourceManager.GetString("AgreementDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement No.
        /// </summary>
        internal static string AgreementNoLbl {
            get {
                return ResourceManager.GetString("AgreementNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Date.
        /// </summary>
        internal static string AgrmntDtLbl {
            get {
                return ResourceManager.GetString("AgrmntDtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement No.
        /// </summary>
        internal static string AgrmntNoLbl {
            get {
                return ResourceManager.GetString("AgrmntNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string ApprovalDateLbl {
            get {
                return ResourceManager.GetString("ApprovalDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By User Id.
        /// </summary>
        internal static string ApprovedByUserIdLbl {
            get {
                return ResourceManager.GetString("ApprovedByUserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Debit Indicator.
        /// </summary>
        internal static string AutoDebitIndChk {
            get {
                return ResourceManager.GetString("AutoDebitIndChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Direct Debit Indicator.
        /// </summary>
        internal static string AutoDebitIndLbl {
            get {
                return ResourceManager.GetString("AutoDebitIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account No.
        /// </summary>
        internal static string BankAccountNoLbl {
            get {
                return ResourceManager.GetString("BankAccountNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Name.
        /// </summary>
        internal static string BankAcctNameLbl {
            get {
                return ResourceManager.GetString("BankAcctNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account No.
        /// </summary>
        internal static string BankAcctNoLbl {
            get {
                return ResourceManager.GetString("BankAcctNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Direct Debit Indicator.
        /// </summary>
        internal static string BankDirectDebitIndChk {
            get {
                return ResourceManager.GetString("BankDirectDebitIndChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Direct Debit Indicator.
        /// </summary>
        internal static string BankDirectDebitIndicatorLbl {
            get {
                return ResourceManager.GetString("BankDirectDebitIndicatorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string BusinessNameLbl {
            get {
                return ResourceManager.GetString("BusinessNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant No..
        /// </summary>
        internal static string BusnLocLbl {
            get {
                return ResourceManager.GetString("BusnLocLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string BusnNameLbl {
            get {
                return ResourceManager.GetString("BusnNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment.
        /// </summary>
        internal static string BusnSizeLbl {
            get {
                return ResourceManager.GetString("BusnSizeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Date.
        /// </summary>
        internal static string CancelDateLbl {
            get {
                return ResourceManager.GetString("CancelDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registered Date.
        /// </summary>
        internal static string CoRegDateLbl {
            get {
                return ResourceManager.GetString("CoRegDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registered Name.
        /// </summary>
        internal static string CoRegNameLbl {
            get {
                return ResourceManager.GetString("CoRegNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registered No.
        /// </summary>
        internal static string CoRegNoLbl {
            get {
                return ResourceManager.GetString("CoRegNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDateLbl {
            get {
                return ResourceManager.GetString("CreationDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Site Id.
        /// </summary>
        internal static string CurrentSiteIdLbl {
            get {
                return ResourceManager.GetString("CurrentSiteIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut-Off Date.
        /// </summary>
        internal static string CutoffDateLbl {
            get {
                return ResourceManager.GetString("CutoffDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut-Off Time.
        /// </summary>
        internal static string CutOffTimeLbl {
            get {
                return ResourceManager.GetString("CutOffTimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Date.
        /// </summary>
        internal static string CycleDateLbl {
            get {
                return ResourceManager.GetString("CycleDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Business As (DBA).
        /// </summary>
        internal static string DBANameLbl {
            get {
                return ResourceManager.GetString("DBANameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Contact.
        /// </summary>
        internal static string DealerContactLbl {
            get {
                return ResourceManager.GetString("DealerContactLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Name.
        /// </summary>
        internal static string DealerNameLbl {
            get {
                return ResourceManager.GetString("DealerNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date From.
        /// </summary>
        internal static string EffDateFromLbl {
            get {
                return ResourceManager.GetString("EffDateFromLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date To.
        /// </summary>
        internal static string EffDateToLbl {
            get {
                return ResourceManager.GetString("EffDateToLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsed By User Id.
        /// </summary>
        internal static string EndorsedByUserIdLbl {
            get {
                return ResourceManager.GetString("EndorsedByUserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsed Date.
        /// </summary>
        internal static string EndorsedDateLbl {
            get {
                return ResourceManager.GetString("EndorsedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Id.
        /// </summary>
        internal static string EntityIdLbl {
            get {
                return ResourceManager.GetString("EntityIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Id.
        /// </summary>
        internal static string EnttIdLbl {
            get {
                return ResourceManager.GetString("EnttIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Account Ind..
        /// </summary>
        internal static string FloatAcctIndLbl {
            get {
                return ResourceManager.GetString("FloatAcctIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Limit.
        /// </summary>
        internal static string FloorLimitLbl {
            get {
                return ResourceManager.GetString("FloorLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant No..
        /// </summary>
        internal static string FromMerchantIdLbl {
            get {
                return ResourceManager.GetString("FromMerchantIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        internal static string LastUpdDateLbl {
            get {
                return ResourceManager.GetString("LastUpdDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        internal static string MerchantNoLbl {
            get {
                return ResourceManager.GetString("MerchantNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDR (%).
        /// </summary>
        internal static string MsfLbl {
            get {
                return ResourceManager.GetString("MsfLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Site Id.
        /// </summary>
        internal static string NewSiteIdLbl {
            get {
                return ResourceManager.GetString("NewSiteIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Ownership To.
        /// </summary>
        internal static string OwnershipToLbl {
            get {
                return ResourceManager.GetString("OwnershipToLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership Transfer Date.
        /// </summary>
        internal static string OwnershipTrsfDateLbl {
            get {
                return ResourceManager.GetString("OwnershipTrsfDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Ref No.
        /// </summary>
        internal static string PartnerRefNoLbl {
            get {
                return ResourceManager.GetString("PartnerRefNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee Name.
        /// </summary>
        internal static string PayeeNameLbl {
            get {
                return ResourceManager.GetString("PayeeNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms.
        /// </summary>
        internal static string PaymentTermsLbl {
            get {
                return ResourceManager.GetString("PaymentTermsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Name.
        /// </summary>
        internal static string PersonInChargeLbl {
            get {
                return ResourceManager.GetString("PersonInChargeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Name.
        /// </summary>
        internal static string PICLbl {
            get {
                return ResourceManager.GetString("PICLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCodeLbl {
            get {
                return ResourceManager.GetString("PostalCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Code.
        /// </summary>
        internal static string RefcdLbl {
            get {
                return ResourceManager.GetString("RefcdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string RemarksLbl {
            get {
                return ResourceManager.GetString("RemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP No.
        /// </summary>
        internal static string SAPNoLbl {
            get {
                return ResourceManager.GetString("SAPNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Business As - City.
        /// </summary>
        internal static string SelectDBACityDdl {
            get {
                return ResourceManager.GetString("SelectDBACityDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Business As - Region.
        /// </summary>
        internal static string SelectDBARegionDdl {
            get {
                return ResourceManager.GetString("SelectDBARegionDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Business As - State.
        /// </summary>
        internal static string SelectDBAStateDdl {
            get {
                return ResourceManager.GetString("SelectDBAStateDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        internal static string SelectedAddressTypeDdl {
            get {
                return ResourceManager.GetString("SelectedAddressTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliated With (Corporate Code).
        /// </summary>
        internal static string SelectedAffiliatedWithCorpCodeDdl {
            get {
                return ResourceManager.GetString("SelectedAffiliatedWithCorpCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        internal static string SelectedAreaCodeDdl {
            get {
                return ResourceManager.GetString("SelectedAreaCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Type.
        /// </summary>
        internal static string selectedBankAccountTypeDdl {
            get {
                return ResourceManager.GetString("selectedBankAccountTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string SelectedBankAcctNameDdl {
            get {
                return ResourceManager.GetString("SelectedBankAcctNameDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Type.
        /// </summary>
        internal static string selectedBankAcctTypeDdl {
            get {
                return ResourceManager.GetString("selectedBankAcctTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch Code.
        /// </summary>
        internal static string SelectedBankBranchCdDdl {
            get {
                return ResourceManager.GetString("SelectedBankBranchCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch Code.
        /// </summary>
        internal static string SelectedBankBranchCodeDdl {
            get {
                return ResourceManager.GetString("SelectedBankBranchCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string SelectedBankNameDdl {
            get {
                return ResourceManager.GetString("SelectedBankNameDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Establishment.
        /// </summary>
        internal static string SelectedBusnEstDdl {
            get {
                return ResourceManager.GetString("SelectedBusnEstDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOSO.
        /// </summary>
        internal static string SelectedBusnModelDdl {
            get {
                return ResourceManager.GetString("SelectedBusnModelDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Size.
        /// </summary>
        internal static string SelectedBusnSizeDdl {
            get {
                return ResourceManager.GetString("SelectedBusnSizeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string SelectedCityDdl {
            get {
                return ResourceManager.GetString("SelectedCityDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string SelectedCountryDdl {
            get {
                return ResourceManager.GetString("SelectedCountryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string selectedCurrentStatusDdl {
            get {
                return ResourceManager.GetString("selectedCurrentStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle No.
        /// </summary>
        internal static string SelectedCycleNoDdl {
            get {
                return ResourceManager.GetString("SelectedCycleNoDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle No.
        /// </summary>
        internal static string SelectedcycNoDdl {
            get {
                return ResourceManager.GetString("SelectedcycNoDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBA Region.
        /// </summary>
        internal static string SelectedDBARegionDdl {
            get {
                return ResourceManager.GetString("SelectedDBARegionDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Business As-State.
        /// </summary>
        internal static string SelectedDBAStateDdl {
            get {
                return ResourceManager.GetString("SelectedDBAStateDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Indicator.
        /// </summary>
        internal static string SelectedMailingIndicatorDdl {
            get {
                return ResourceManager.GetString("SelectedMailingIndicatorDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Category Code.
        /// </summary>
        internal static string SelectedMCCDdl {
            get {
                return ResourceManager.GetString("SelectedMCCDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        internal static string SelectedOwnershipDdl {
            get {
                return ResourceManager.GetString("SelectedOwnershipDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        internal static string selectedOwnershsipDdl {
            get {
                return ResourceManager.GetString("selectedOwnershsipDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        internal static string SelectedPaymtModeDdl {
            get {
                return ResourceManager.GetString("SelectedPaymtModeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string SelectedProdCdDdl {
            get {
                return ResourceManager.GetString("SelectedProdCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        internal static string SelectedReasonCodeDdl {
            get {
                return ResourceManager.GetString("SelectedReasonCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        internal static string SelectedReasonCodeLbl {
            get {
                return ResourceManager.GetString("SelectedReasonCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string SelectedRegionDdl {
            get {
                return ResourceManager.GetString("SelectedRegionDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Industry Code.
        /// </summary>
        internal static string SelectedSICDdl {
            get {
                return ResourceManager.GetString("SelectedSICDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string SelectedStateDdl {
            get {
                return ResourceManager.GetString("SelectedStateDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        internal static string SelectedTaxCodeDdl {
            get {
                return ResourceManager.GetString("SelectedTaxCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Id.
        /// </summary>
        internal static string SiteIdLbl {
            get {
                return ResourceManager.GetString("SiteIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string SourceCdLbl {
            get {
                return ResourceManager.GetString("SourceCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Reference No.
        /// </summary>
        internal static string SourceRefNoLbl {
            get {
                return ResourceManager.GetString("SourceRefNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Print Indicator.
        /// </summary>
        internal static string StmtPrintIndLbl {
            get {
                return ResourceManager.GetString("StmtPrintIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        internal static string TaxIdLbl {
            get {
                return ResourceManager.GetString("TaxIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Registration Name.
        /// </summary>
        internal static string TaxRegistrationNameLbl {
            get {
                return ResourceManager.GetString("TaxRegistrationNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topup Amt.
        /// </summary>
        internal static string TopupAmtLbl {
            get {
                return ResourceManager.GetString("TopupAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topup Limit.
        /// </summary>
        internal static string TopupLimitLbl {
            get {
                return ResourceManager.GetString("TopupLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Registration Name.
        /// </summary>
        internal static string TxnCodeDdl {
            get {
                return ResourceManager.GetString("TxnCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string UserIDLbl {
            get {
                return ResourceManager.GetString("UserIDLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Rate.
        /// </summary>
        internal static string VATRateLbl {
            get {
                return ResourceManager.GetString("VATRateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Holding Tax Indicator.
        /// </summary>
        internal static string WithholdingTaxIndLbl {
            get {
                return ResourceManager.GetString("WithholdingTaxIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Holding Tax Rate.
        /// </summary>
        internal static string WithholdingTaxRateLbl {
            get {
                return ResourceManager.GetString("WithholdingTaxRateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Hold Payment Flag.
        /// </summary>
        internal static string WithholdPaymtFlagLbl {
            get {
                return ResourceManager.GetString("WithholdPaymtFlagLbl", resourceCulture);
            }
        }
    }
}
