//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendCorporate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendCorporate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendCorporate", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string Addr1Lbl {
            get {
                return ResourceManager.GetString("Addr1Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Addr2Lbl {
            get {
                return ResourceManager.GetString("Addr2Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        internal static string Addr3Lbl {
            get {
                return ResourceManager.GetString("Addr3Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Fax.
        /// </summary>
        internal static string CmpyFaxLbl {
            get {
                return ResourceManager.GetString("CmpyFaxLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Indicator.
        /// </summary>
        internal static string ComplexIndLbl {
            get {
                return ResourceManager.GetString("ComplexIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string ContactNameLbl {
            get {
                return ResourceManager.GetString("ContactNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string ContactNoLbl {
            get {
                return ResourceManager.GetString("ContactNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Code.
        /// </summary>
        internal static string CorpCdLbl {
            get {
                return ResourceManager.GetString("CorpCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Name.
        /// </summary>
        internal static string CorpNameLbl {
            get {
                return ResourceManager.GetString("CorpNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddrLbl {
            get {
                return ResourceManager.GetString("EmailAddrLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Center.
        /// </summary>
        internal static string InvBillIndLbl {
            get {
                return ResourceManager.GetString("InvBillIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string MobileNoLbl {
            get {
                return ResourceManager.GetString("MobileNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorised Signatory.
        /// </summary>
        internal static string PICLbl {
            get {
                return ResourceManager.GetString("PICLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Center.
        /// </summary>
        internal static string PymtIndLbl {
            get {
                return ResourceManager.GetString("PymtIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Code.
        /// </summary>
        internal static string SelectedAddrCdDdl {
            get {
                return ResourceManager.GetString("SelectedAddrCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Code.
        /// </summary>
        internal static string SelectedContactCdDdl {
            get {
                return ResourceManager.GetString("SelectedContactCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        internal static string SelectedContactTypeDdl {
            get {
                return ResourceManager.GetString("SelectedContactTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string SelectedCtryDdl {
            get {
                return ResourceManager.GetString("SelectedCtryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string SelectedStateDdl {
            get {
                return ResourceManager.GetString("SelectedStateDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Credit Limit.
        /// </summary>
        internal static string TradeCreditLimitLbl {
            get {
                return ResourceManager.GetString("TradeCreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCd.
        /// </summary>
        internal static string ZipCdLbl {
            get {
                return ResourceManager.GetString("ZipCdLbl", resourceCulture);
            }
        }
    }
}
