//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendManualSlip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendManualSlip() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendManualSlip", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountLbl {
            get {
                return ResourceManager.GetString("AmountLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code.
        /// </summary>
        internal static string AppvCdLbl {
            get {
                return ResourceManager.GetString("AppvCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Product Item.
        /// </summary>
        internal static string ArrayCntLbl {
            get {
                return ResourceManager.GetString("ArrayCntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Card Expired.
        /// </summary>
        internal static string AuthCardExpLbl {
            get {
                return ResourceManager.GetString("AuthCardExpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Card No.
        /// </summary>
        internal static string AuthCardNoLbl {
            get {
                return ResourceManager.GetString("AuthCardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code.
        /// </summary>
        internal static string AuthNoLbl {
            get {
                return ResourceManager.GetString("AuthNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Entry Status.
        /// </summary>
        internal static string BatchEntryStsLbl {
            get {
                return ResourceManager.GetString("BatchEntryStsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Id.
        /// </summary>
        internal static string BatchIdLbl {
            get {
                return ResourceManager.GetString("BatchIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        internal static string BusnLocationLbl {
            get {
                return ResourceManager.GetString("BusnLocationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Expired.
        /// </summary>
        internal static string CardExpireLbl {
            get {
                return ResourceManager.GetString("CardExpireLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        internal static string CardNoLbl {
            get {
                return ResourceManager.GetString("CardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration Date.
        /// </summary>
        internal static string CoRegDateLbl {
            get {
                return ResourceManager.GetString("CoRegDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescpLbl {
            get {
                return ResourceManager.GetString("DescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string DisplayTotalAmtLbl {
            get {
                return ResourceManager.GetString("DisplayTotalAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Code.
        /// </summary>
        internal static string DriverCdLbl {
            get {
                return ResourceManager.GetString("DriverCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string InvoiceNoLbl {
            get {
                return ResourceManager.GetString("InvoiceNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        internal static string LastUpdDateLbl {
            get {
                return ResourceManager.GetString("LastUpdDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Reading.
        /// </summary>
        internal static string OdometerLbl {
            get {
                return ResourceManager.GetString("OdometerLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Batch No.
        /// </summary>
        internal static string OrigBatchNoLbl {
            get {
                return ResourceManager.GetString("OrigBatchNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Amount.
        /// </summary>
        internal static string ProdAmtLbl {
            get {
                return ResourceManager.GetString("ProdAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        internal static string ProdDescLbl {
            get {
                return ResourceManager.GetString("ProdDescLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string QuantityLbl {
            get {
                return ResourceManager.GetString("QuantityLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt No.
        /// </summary>
        internal static string RcptNoLbl {
            get {
                return ResourceManager.GetString("RcptNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval Reference No.
        /// </summary>
        internal static string RrnLbl {
            get {
                return ResourceManager.GetString("RrnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string SelectedProdCdDdl {
            get {
                return ResourceManager.GetString("SelectedProdCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SelectedStsDdl {
            get {
                return ResourceManager.GetString("SelectedStsDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Id.
        /// </summary>
        internal static string SelectedTermIdDdl {
            get {
                return ResourceManager.GetString("SelectedTermIdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Code.
        /// </summary>
        internal static string SelectedTxnCdDdl {
            get {
                return ResourceManager.GetString("SelectedTxnCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Code.
        /// </summary>
        internal static string SelectedVATCdDdl {
            get {
                return ResourceManager.GetString("SelectedVATCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Code.
        /// </summary>
        internal static string SelectedVATCDdl {
            get {
                return ResourceManager.GetString("SelectedVATCDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle Date.
        /// </summary>
        internal static string SettleDateLbl {
            get {
                return ResourceManager.GetString("SettleDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle Id.
        /// </summary>
        internal static string SettleIdLbl {
            get {
                return ResourceManager.GetString("SettleIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Amount.
        /// </summary>
        internal static string ShownTxnAmtLbl {
            get {
                return ResourceManager.GetString("ShownTxnAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Id.
        /// </summary>
        internal static string SiteIdLbl {
            get {
                return ResourceManager.GetString("SiteIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan.
        /// </summary>
        internal static string StansLbl {
            get {
                return ResourceManager.GetString("StansLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmtLbl {
            get {
                return ResourceManager.GetString("TotalAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        internal static string TotalCntLbl {
            get {
                return ResourceManager.GetString("TotalCntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Amount.
        /// </summary>
        internal static string TxnAmtLbl {
            get {
                return ResourceManager.GetString("TxnAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Date.
        /// </summary>
        internal static string TxnDateLbl {
            get {
                return ResourceManager.GetString("TxnDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Description.
        /// </summary>
        internal static string TxnDescpLbl {
            get {
                return ResourceManager.GetString("TxnDescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Detail Id.
        /// </summary>
        internal static string TxnDetailIdLbl {
            get {
                return ResourceManager.GetString("TxnDetailIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Id.
        /// </summary>
        internal static string TxnIdLbl {
            get {
                return ResourceManager.GetString("TxnIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPriceLbl {
            get {
                return ResourceManager.GetString("UnitPriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string UserIdLbl {
            get {
                return ResourceManager.GetString("UserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Amount.
        /// </summary>
        internal static string VATAmtLbl {
            get {
                return ResourceManager.GetString("VATAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST No.
        /// </summary>
        internal static string VATNoLbl {
            get {
                return ResourceManager.GetString("VATNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Rate.
        /// </summary>
        internal static string VATRateLbl {
            get {
                return ResourceManager.GetString("VATRateLbl", resourceCulture);
            }
        }
    }
}
