//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendAccount {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendAccount() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendAccount", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountLbl {
            get {
                return ResourceManager.GetString("AccountLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string AccountNameLbl {
            get {
                return ResourceManager.GetString("AccountNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accrued Credit Usage.
        /// </summary>
        internal static string AccrdCrdtUsgLbl {
            get {
                return ResourceManager.GetString("AccrdCrdtUsgLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accrued Interest.
        /// </summary>
        internal static string AccrdInterestLbl {
            get {
                return ResourceManager.GetString("AccrdInterestLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string AcctNoLbl {
            get {
                return ResourceManager.GetString("AcctNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string AdminEmailLbl {
            get {
                return ResourceManager.GetString("AdminEmailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Credit Limit.
        /// </summary>
        internal static string AllowCreditLimitLbl {
            get {
                return ResourceManager.GetString("AllowCreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Limit Per Transaction.
        /// </summary>
        internal static string AmtLimitPerTxnLbl {
            get {
                return ResourceManager.GetString("AmtLimitPerTxnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Creation Date.
        /// </summary>
        internal static string ApplCreationDateLbl {
            get {
                return ResourceManager.GetString("ApplCreationDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Id.
        /// </summary>
        internal static string ApplIdLbl {
            get {
                return ResourceManager.GetString("ApplIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Reference.
        /// </summary>
        internal static string ApplRefLbl {
            get {
                return ResourceManager.GetString("ApplRefLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Transffered Date.
        /// </summary>
        internal static string ApplTransfferedDateLbl {
            get {
                return ResourceManager.GetString("ApplTransfferedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Credit Limit.
        /// </summary>
        internal static string ApprovedCreditLimitLbl {
            get {
                return ResourceManager.GetString("ApprovedCreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        internal static string AppvDateEDPLbl {
            get {
                return ResourceManager.GetString("AppvDateEDPLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string AppvUserIdCredOffLbl {
            get {
                return ResourceManager.GetString("AppvUserIdCredOffLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string AppvUserIdEDPLbl {
            get {
                return ResourceManager.GetString("AppvUserIdEDPLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Id.
        /// </summary>
        internal static string AuditIdLbl {
            get {
                return ResourceManager.GetString("AuditIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Signatory.
        /// </summary>
        internal static string AuthSignatoryLbl {
            get {
                return ResourceManager.GetString("AuthSignatoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (g) Available Credit Limit (g = i - f).
        /// </summary>
        internal static string AvailableCredLimitLbl {
            get {
                return ResourceManager.GetString("AvailableCredLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance date.
        /// </summary>
        internal static string BalDateLbl {
            get {
                return ResourceManager.GetString("BalDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account No.
        /// </summary>
        internal static string BankAcctNoLbl {
            get {
                return ResourceManager.GetString("BankAcctNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch Cd.
        /// </summary>
        internal static string BankBranchCDLbl {
            get {
                return ResourceManager.GetString("BankBranchCDLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Deposit Ref No..
        /// </summary>
        internal static string BankBranchCodeLbl {
            get {
                return ResourceManager.GetString("BankBranchCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (d) Batch Amount.
        /// </summary>
        internal static string BatchAmtLbl {
            get {
                return ResourceManager.GetString("BatchAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Amount.
        /// </summary>
        internal static string BillingTxnAmtLbl {
            get {
                return ResourceManager.GetString("BillingTxnAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Date.
        /// </summary>
        internal static string BlockedDateLbl {
            get {
                return ResourceManager.GetString("BlockedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking date.
        /// </summary>
        internal static string BookingDtLbl {
            get {
                return ResourceManager.GetString("BookingDtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        internal static string CardNoLbl {
            get {
                return ResourceManager.GetString("CardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Status.
        /// </summary>
        internal static string CardStsLbl {
            get {
                return ResourceManager.GetString("CardStsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No./Payment Reference No..
        /// </summary>
        internal static string CheqNoLbl {
            get {
                return ResourceManager.GetString("CheqNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Date.
        /// </summary>
        internal static string ClosedDateLbl {
            get {
                return ResourceManager.GetString("ClosedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (f) Closing Balance (f = a + b + c).
        /// </summary>
        internal static string ClosingBalLbl {
            get {
                return ResourceManager.GetString("ClosingBalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration No.
        /// </summary>
        internal static string CmpyRegsNoLbl {
            get {
                return ResourceManager.GetString("CmpyRegsNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Id.
        /// </summary>
        internal static string CollectionIdLbl {
            get {
                return ResourceManager.GetString("CollectionIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Emboss Name.
        /// </summary>
        internal static string CompanyEmbNameLbl {
            get {
                return ResourceManager.GetString("CompanyEmbNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyNameLbl {
            get {
                return ResourceManager.GetString("CompanyNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string ContactPersonLbl {
            get {
                return ResourceManager.GetString("ContactPersonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CreatedByLbl {
            get {
                return ResourceManager.GetString("CreatedByLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDateLbl {
            get {
                return ResourceManager.GetString("CreationDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationdtLbl {
            get {
                return ResourceManager.GetString("CreationdtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit.
        /// </summary>
        internal static string CreditLimitLbl {
            get {
                return ResourceManager.GetString("CreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cr Allowance Factor (%).
        /// </summary>
        internal static string CredtAllowanceFactLbl {
            get {
                return ResourceManager.GetString("CredtAllowanceFactLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off.
        /// </summary>
        internal static string CutOffLbl {
            get {
                return ResourceManager.GetString("CutOffLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Credit Indicator.
        /// </summary>
        internal static string DbCrIndLbl {
            get {
                return ResourceManager.GetString("DbCrIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        internal static string DeftBusnLocationLbl {
            get {
                return ResourceManager.GetString("DeftBusnLocationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deft Terminal Id.
        /// </summary>
        internal static string DeftTermIdLbl {
            get {
                return ResourceManager.GetString("DeftTermIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Amount.
        /// </summary>
        internal static string DepositAmtLbl {
            get {
                return ResourceManager.GetString("DepositAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Bank Account No.
        /// </summary>
        internal static string DepositBankAcctNoLbl {
            get {
                return ResourceManager.GetString("DepositBankAcctNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Bank Branch Cd.
        /// </summary>
        internal static string DepositBankBranchCDLbl {
            get {
                return ResourceManager.GetString("DepositBankBranchCDLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Exp.
        /// </summary>
        internal static string DepositExpLbl {
            get {
                return ResourceManager.GetString("DepositExpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit From Date.
        /// </summary>
        internal static string DepositFromDateLbl {
            get {
                return ResourceManager.GetString("DepositFromDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit To Date.
        /// </summary>
        internal static string DepositToDateLbl {
            get {
                return ResourceManager.GetString("DepositToDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescpLbl {
            get {
                return ResourceManager.GetString("DescpLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionLbl {
            get {
                return ResourceManager.GetString("DescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit Indicator.
        /// </summary>
        internal static string DirectDebitIndLbl {
            get {
                return ResourceManager.GetString("DirectDebitIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string DueDtLbl {
            get {
                return ResourceManager.GetString("DueDtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective From Date.
        /// </summary>
        internal static string EffDateFromLbl {
            get {
                return ResourceManager.GetString("EffDateFromLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective To Date.
        /// </summary>
        internal static string EffDateToLbl {
            get {
                return ResourceManager.GetString("EffDateToLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement From Date.
        /// </summary>
        internal static string EffFromDateLbl {
            get {
                return ResourceManager.GetString("EffFromDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement To Date.
        /// </summary>
        internal static string EffToDateLbl {
            get {
                return ResourceManager.GetString("EffToDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsedby.
        /// </summary>
        internal static string EndorsedByLbl {
            get {
                return ResourceManager.GetString("EndorsedByLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorseddate.
        /// </summary>
        internal static string EndorsedDateLbl {
            get {
                return ResourceManager.GetString("EndorsedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Id.
        /// </summary>
        internal static string EntityIdLbl {
            get {
                return ResourceManager.GetString("EntityIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        internal static string EventDateLbl {
            get {
                return ResourceManager.GetString("EventDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id.
        /// </summary>
        internal static string EventIdLbl {
            get {
                return ResourceManager.GetString("EventIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string ExpDateLbl {
            get {
                return ResourceManager.GetString("ExpDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace Period.
        /// </summary>
        internal static string GracePeriodLbl {
            get {
                return ResourceManager.GetString("GracePeriodLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (b) Instant Amount.
        /// </summary>
        internal static string InstantAmtLbl {
            get {
                return ResourceManager.GetString("InstantAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Points.
        /// </summary>
        internal static string InstantPtsLbl {
            get {
                return ResourceManager.GetString("InstantPtsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Billing Indicator.
        /// </summary>
        internal static string InvoiceBillingIndicatorLbl {
            get {
                return ResourceManager.GetString("InvoiceBillingIndicatorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Invoice Indicator.
        /// </summary>
        internal static string InvoiceIndCopyLbl {
            get {
                return ResourceManager.GetString("InvoiceIndCopyLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string InvoiceNoLbl {
            get {
                return ResourceManager.GetString("InvoiceNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment Date.
        /// </summary>
        internal static string LastPaymtDateLbl {
            get {
                return ResourceManager.GetString("LastPaymtDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment Received.
        /// </summary>
        internal static string LastPaymtReceivedLbl {
            get {
                return ResourceManager.GetString("LastPaymtReceivedLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment Type.
        /// </summary>
        internal static string LastPaymtTypeLbl {
            get {
                return ResourceManager.GetString("LastPaymtTypeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Subsidy Date.
        /// </summary>
        internal static string LastSubsidyDateLbl {
            get {
                return ResourceManager.GetString("LastSubsidyDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        internal static string LastUpdDateLbl {
            get {
                return ResourceManager.GetString("LastUpdDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Of Credit Provider.
        /// </summary>
        internal static string LineOfCredtProviderLbl {
            get {
                return ResourceManager.GetString("LineOfCredtProviderLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litre Limit Per Transaction.
        /// </summary>
        internal static string LitreLimitPerTxnLbl {
            get {
                return ResourceManager.GetString("LitreLimitPerTxnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMS Account No..
        /// </summary>
        internal static string LoyaltyCardNoLbl {
            get {
                return ResourceManager.GetString("LoyaltyCardNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement date.
        /// </summary>
        internal static string MovementDtLbl {
            get {
                return ResourceManager.GetString("MovementDtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Comment.
        /// </summary>
        internal static string NewCommentLbl {
            get {
                return ResourceManager.GetString("NewCommentLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Interval Review Date.
        /// </summary>
        internal static string NRIDLbl {
            get {
                return ResourceManager.GetString("NRIDLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (e) Offline Amount.
        /// </summary>
        internal static string OfflineAmtLbl {
            get {
                return ResourceManager.GetString("OfflineAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) Online Amount.
        /// </summary>
        internal static string OnlineAmtLbl {
            get {
                return ResourceManager.GetString("OnlineAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Indicator.
        /// </summary>
        internal static string OnlineIndicatorLbl {
            get {
                return ResourceManager.GetString("OnlineIndicatorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (a) Opening Balance.
        /// </summary>
        internal static string OpeningBalLbl {
            get {
                return ResourceManager.GetString("OpeningBalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Points Balance.
        /// </summary>
        internal static string OpeningPtsBalLbl {
            get {
                return ResourceManager.GetString("OpeningPtsBalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides Account Expiry Date.
        /// </summary>
        internal static string OvrStartDateLbl {
            get {
                return ResourceManager.GetString("OvrStartDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides Status Tagged By User Id.
        /// </summary>
        internal static string OvrStatusTaggedByUserIdLbl {
            get {
                return ResourceManager.GetString("OvrStatusTaggedByUserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Advice Billing Indicator.
        /// </summary>
        internal static string PayAdviceBillingIndicatorLbl {
            get {
                return ResourceManager.GetString("PayAdviceBillingIndicatorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee Code.
        /// </summary>
        internal static string PayeeCdLbl {
            get {
                return ResourceManager.GetString("PayeeCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term.
        /// </summary>
        internal static string PaymtTermLbl {
            get {
                return ResourceManager.GetString("PaymtTermLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person in Charge.
        /// </summary>
        internal static string PersoninChargeLbl {
            get {
                return ResourceManager.GetString("PersoninChargeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP Point Balance.
        /// </summary>
        internal static string PointBalanceLbl {
            get {
                return ResourceManager.GetString("PointBalanceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPR Expiry.
        /// </summary>
        internal static string pprExpiryLbl {
            get {
                return ResourceManager.GetString("pprExpiryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPR Grace Period.
        /// </summary>
        internal static string PPRGracePeriodLbl {
            get {
                return ResourceManager.GetString("PPRGracePeriodLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt Payment Rebate (%).
        /// </summary>
        internal static string PromPaymtRebateLbl {
            get {
                return ResourceManager.GetString("PromPaymtRebateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Credit Limit.
        /// </summary>
        internal static string ProposeCreditLimitLbl {
            get {
                return ResourceManager.GetString("ProposeCreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Security Amount.
        /// </summary>
        internal static string ProposeSecurityAmtDdl {
            get {
                return ResourceManager.GetString("ProposeSecurityAmtDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Security Amount.
        /// </summary>
        internal static string ProposeSecurityAmtLbl {
            get {
                return ResourceManager.GetString("ProposeSecurityAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Id.
        /// </summary>
        internal static string PyTxnIdLbl {
            get {
                return ResourceManager.GetString("PyTxnIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota From Date.
        /// </summary>
        internal static string QuotaFromDateLbl {
            get {
                return ResourceManager.GetString("QuotaFromDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Limit.
        /// </summary>
        internal static string QuotaLimitLbl {
            get {
                return ResourceManager.GetString("QuotaLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota To Date.
        /// </summary>
        internal static string QuotaToDateLbl {
            get {
                return ResourceManager.GetString("QuotaToDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Usage.
        /// </summary>
        internal static string QuotaUsageLbl {
            get {
                return ResourceManager.GetString("QuotaUsageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Credit Limit.
        /// </summary>
        internal static string RecommendCreditLimitLbl {
            get {
                return ResourceManager.GetString("RecommendCreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Security Amount.
        /// </summary>
        internal static string RecommendSecurityAmtLbl {
            get {
                return ResourceManager.GetString("RecommendSecurityAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Document.
        /// </summary>
        internal static string RefDocLbl {
            get {
                return ResourceManager.GetString("RefDocLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Reg No..
        /// </summary>
        internal static string RefferenceLbl {
            get {
                return ResourceManager.GetString("RefferenceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Id.
        /// </summary>
        internal static string RefIdLbl {
            get {
                return ResourceManager.GetString("RefIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Key.
        /// </summary>
        internal static string RefKeyLbl {
            get {
                return ResourceManager.GetString("RefKeyLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type.
        /// </summary>
        internal static string RefTypeLbl {
            get {
                return ResourceManager.GetString("RefTypeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration Date.
        /// </summary>
        internal static string RegsDateLbl {
            get {
                return ResourceManager.GetString("RegsDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string RemarksLbl {
            get {
                return ResourceManager.GetString("RemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder DateTime.
        /// </summary>
        internal static string ReminderDatetimeLbl {
            get {
                return ResourceManager.GetString("ReminderDatetimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Activation.
        /// </summary>
        internal static string ResendEmailLbl {
            get {
                return ResourceManager.GetString("ResendEmailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Proposal.
        /// </summary>
        internal static string SaleProposalLbl {
            get {
                return ResourceManager.GetString("SaleProposalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer No.
        /// </summary>
        internal static string SapNoLbl {
            get {
                return ResourceManager.GetString("SapNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Ref No.
        /// </summary>
        internal static string SAPRefNoLbl {
            get {
                return ResourceManager.GetString("SAPRefNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Amount.
        /// </summary>
        internal static string SecurityAmtLbl {
            get {
                return ResourceManager.GetString("SecurityAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string SelectedAccountTypeDdl {
            get {
                return ResourceManager.GetString("SelectedAccountTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SelectedAcctStsDdl {
            get {
                return ResourceManager.GetString("SelectedAcctStsDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate.
        /// </summary>
        internal static string SelectedAffiliateDdl {
            get {
                return ResourceManager.GetString("SelectedAffiliateDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code.
        /// </summary>
        internal static string SelectedAppvCdDdl {
            get {
                return ResourceManager.GetString("SelectedAppvCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Status.
        /// </summary>
        internal static string SelectedAppvStsCredOffDdl {
            get {
                return ResourceManager.GetString("SelectedAppvStsCredOffDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Status.
        /// </summary>
        internal static string SelectedAppvStsEDPDdl {
            get {
                return ResourceManager.GetString("SelectedAppvStsEDPDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Deposit Requirement.
        /// </summary>
        internal static string SelectedAssesmtTypeDdl {
            get {
                return ResourceManager.GetString("SelectedAssesmtTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Deposit Requirement.
        /// </summary>
        internal static string SelectedAssessmentTypeDdl {
            get {
                return ResourceManager.GetString("SelectedAssessmentTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Collector.
        /// </summary>
        internal static string SelectedAssignCollectorDdl {
            get {
                return ResourceManager.GetString("SelectedAssignCollectorDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Type.
        /// </summary>
        internal static string SelectedBankAcctTypeDdl {
            get {
                return ResourceManager.GetString("SelectedBankAcctTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string selectedBankNameDdl {
            get {
                return ResourceManager.GetString("selectedBankNameDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category.
        /// </summary>
        internal static string SelectedBusnCategoryDdl {
            get {
                return ResourceManager.GetString("SelectedBusnCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Establishment.
        /// </summary>
        internal static string SelectedBusnEstablishmentDdl {
            get {
                return ResourceManager.GetString("SelectedBusnEstablishmentDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string SelectedCategoryDdl {
            get {
                return ResourceManager.GetString("SelectedCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Class.
        /// </summary>
        internal static string SelectedClientClassDdl {
            get {
                return ResourceManager.GetString("SelectedClientClassDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Type.
        /// </summary>
        internal static string selectedClientTypeDdl {
            get {
                return ResourceManager.GetString("selectedClientTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        internal static string SelectedCompanyTypeDdl {
            get {
                return ResourceManager.GetString("SelectedCompanyTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Code.
        /// </summary>
        internal static string SelectedCorpNameDdl {
            get {
                return ResourceManager.GetString("SelectedCorpNameDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Centre.
        /// </summary>
        internal static string SelectedCostCentreDdl {
            get {
                return ResourceManager.GetString("SelectedCostCentreDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SelectedCurrentStatusDdl {
            get {
                return ResourceManager.GetString("SelectedCurrentStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Group.
        /// </summary>
        internal static string SelectedCustomerGroupDdl {
            get {
                return ResourceManager.GetString("SelectedCustomerGroupDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle No.
        /// </summary>
        internal static string SelectedCycNoDdl {
            get {
                return ResourceManager.GetString("SelectedCycNoDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Type.
        /// </summary>
        internal static string SelectedDepositTypeDdl {
            get {
                return ResourceManager.GetString("SelectedDepositTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Plan.
        /// </summary>
        internal static string SelectedDiscPlanDdl {
            get {
                return ResourceManager.GetString("SelectedDiscPlanDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunning Code.
        /// </summary>
        internal static string SelectedDunningCdDdl {
            get {
                return ResourceManager.GetString("SelectedDunningCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Status.
        /// </summary>
        internal static string SelectedEventStsDdl {
            get {
                return ResourceManager.GetString("SelectedEventStsDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        internal static string SelectedEventTypeDdl {
            get {
                return ResourceManager.GetString("SelectedEventTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SelectedLangIdDdl {
            get {
                return ResourceManager.GetString("SelectedLangIdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string SelectedModuleDdl {
            get {
                return ResourceManager.GetString("SelectedModuleDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Reinstatement.
        /// </summary>
        internal static string SelectedOvrStatusDdl {
            get {
                return ResourceManager.GetString("SelectedOvrStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string SelectedOwnerDdl {
            get {
                return ResourceManager.GetString("SelectedOwnerDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        internal static string SelectedPaymentModeDdl {
            get {
                return ResourceManager.GetString("SelectedPaymentModeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms.
        /// </summary>
        internal static string SelectedPaymentTermDdl {
            get {
                return ResourceManager.GetString("SelectedPaymentTermDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        internal static string SelectedPaymtMethodDdl {
            get {
                return ResourceManager.GetString("SelectedPaymtMethodDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Id.
        /// </summary>
        internal static string SelectedPlanIdDdl {
            get {
                return ResourceManager.GetString("SelectedPlanIdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Type.
        /// </summary>
        internal static string SelectedPlasticTypeDdl {
            get {
                return ResourceManager.GetString("SelectedPlasticTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string SelectedProdCdDdl {
            get {
                return ResourceManager.GetString("SelectedProdCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Type.
        /// </summary>
        internal static string SelectedProdDiscTypeDdl {
            get {
                return ResourceManager.GetString("SelectedProdDiscTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Type.
        /// </summary>
        internal static string SelectedPyTxnCdDdl {
            get {
                return ResourceManager.GetString("SelectedPyTxnCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitative Rating.
        /// </summary>
        internal static string SelectedQualitativeDdl {
            get {
                return ResourceManager.GetString("SelectedQualitativeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantitative Rating.
        /// </summary>
        internal static string SelectedQuantitativeDdl {
            get {
                return ResourceManager.GetString("SelectedQuantitativeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Codes.
        /// </summary>
        internal static string SelectedReasonCodeDdl {
            get {
                return ResourceManager.GetString("SelectedReasonCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Plan.
        /// </summary>
        internal static string SelectedRebatePlanDdl {
            get {
                return ResourceManager.GetString("SelectedRebatePlanDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Category.
        /// </summary>
        internal static string SelectedRiskCategoryDdl {
            get {
                return ResourceManager.GetString("SelectedRiskCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Category.
        /// </summary>
        internal static string SelectedRiskCategryDdl {
            get {
                return ResourceManager.GetString("SelectedRiskCategryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Territory.
        /// </summary>
        internal static string SelectedSaleTerritoryDdl {
            get {
                return ResourceManager.GetString("SelectedSaleTerritoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Industry Code.
        /// </summary>
        internal static string SelectedSICDdl {
            get {
                return ResourceManager.GetString("SelectedSICDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Subsidy Tag.
        /// </summary>
        internal static string SelectedSkdsAcctSubDdl {
            get {
                return ResourceManager.GetString("SelectedSkdsAcctSubDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SelectedStatusDdl {
            get {
                return ResourceManager.GetString("SelectedStatusDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Preference.
        /// </summary>
        internal static string SelectedStmtIndDdl {
            get {
                return ResourceManager.GetString("SelectedStmtIndDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Type.
        /// </summary>
        internal static string SelectedStmtTypeDdl {
            get {
                return ResourceManager.GetString("SelectedStmtTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Status.
        /// </summary>
        internal static string SelectedStsDdl {
            get {
                return ResourceManager.GetString("SelectedStsDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy Level.
        /// </summary>
        internal static string SelectedSubsidyLevelDdl {
            get {
                return ResourceManager.GetString("SelectedSubsidyLevelDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy Type.
        /// </summary>
        internal static string SelectedSubsidyTypeDdl {
            get {
                return ResourceManager.GetString("SelectedSubsidyTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Category.
        /// </summary>
        internal static string SelectedTaxCategoryDdl {
            get {
                return ResourceManager.GetString("SelectedTaxCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Territory.
        /// </summary>
        internal static string SelectedTerritoryCdDdl {
            get {
                return ResourceManager.GetString("SelectedTerritoryCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Area.
        /// </summary>
        internal static string SelectedTradingAreaDdl {
            get {
                return ResourceManager.GetString("SelectedTradingAreaDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Type.
        /// </summary>
        internal static string SelectedTxnCdDdl {
            get {
                return ResourceManager.GetString("SelectedTxnCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Type.
        /// </summary>
        internal static string SelectedTxnTypeDdl {
            get {
                return ResourceManager.GetString("SelectedTxnTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel Subsidy Doc Xref.
        /// </summary>
        internal static string SKDSDocXrefLbl {
            get {
                return ResourceManager.GetString("SKDSDocXrefLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy Litre Quota.
        /// </summary>
        internal static string SKDSLitreQuotaLbl {
            get {
                return ResourceManager.GetString("SKDSLitreQuotaLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy No.
        /// </summary>
        internal static string SKDSNoLbl {
            get {
                return ResourceManager.GetString("SKDSNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel Subsidy Quota.
        /// </summary>
        internal static string SKDSQuotaLbl {
            get {
                return ResourceManager.GetString("SKDSQuotaLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel Subsidy Rate.
        /// </summary>
        internal static string SKDSRateLbl {
            get {
                return ResourceManager.GetString("SKDSRateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel Subsidy Ref.
        /// </summary>
        internal static string SKDSRefLbl {
            get {
                return ResourceManager.GetString("SKDSRefLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel Subsidy Description.
        /// </summary>
        internal static string SksdDespLbl {
            get {
                return ResourceManager.GetString("SksdDespLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string SourceCodeLbl {
            get {
                return ResourceManager.GetString("SourceCodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Reference No.
        /// </summary>
        internal static string SourceRefNoLbl {
            get {
                return ResourceManager.GetString("SourceRefNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Statement Date.
        /// </summary>
        internal static string StmtDateLbl {
            get {
                return ResourceManager.GetString("StmtDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Ind.
        /// </summary>
        internal static string SysIndLbl {
            get {
                return ResourceManager.GetString("SysIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total O/S Balance.
        /// </summary>
        internal static string TARBalLbl {
            get {
                return ResourceManager.GetString("TARBalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        internal static string TaxIdLbl {
            get {
                return ResourceManager.GetString("TaxIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Credit Limit.
        /// </summary>
        internal static string TempCreditLimitLbl {
            get {
                return ResourceManager.GetString("TempCreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated Date.
        /// </summary>
        internal static string TerminatedDateLbl {
            get {
                return ResourceManager.GetString("TerminatedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (i) Total Credit Limit.
        /// </summary>
        internal static string TotalCreditLimitLbl {
            get {
                return ResourceManager.GetString("TotalCreditLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Amount.
        /// </summary>
        internal static string TotAmntLbl {
            get {
                return ResourceManager.GetString("TotAmntLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Point.
        /// </summary>
        internal static string TotptsLbl {
            get {
                return ResourceManager.GetString("TotptsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        internal static string TransactionIdLbl {
            get {
                return ResourceManager.GetString("TransactionIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Limit Per Transaction.
        /// </summary>
        internal static string TxnAmtLimitLbl {
            get {
                return ResourceManager.GetString("TxnAmtLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Code.
        /// </summary>
        internal static string TxnCdLbl {
            get {
                return ResourceManager.GetString("TxnCdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Date.
        /// </summary>
        internal static string TxnDateLbl {
            get {
                return ResourceManager.GetString("TxnDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txn Id.
        /// </summary>
        internal static string TxnidLbl {
            get {
                return ResourceManager.GetString("TxnidLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litre Limit Per Transaction.
        /// </summary>
        internal static string TxnLitLimitLbl {
            get {
                return ResourceManager.GetString("TxnLitLimitLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unposted Amount.
        /// </summary>
        internal static string UnpostedAmtLbl {
            get {
                return ResourceManager.GetString("UnpostedAmtLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unposted Points.
        /// </summary>
        internal static string UnpostedPtsLbl {
            get {
                return ResourceManager.GetString("UnpostedPtsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string UserIdLbl {
            get {
                return ResourceManager.GetString("UserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity Period.
        /// </summary>
        internal static string ValidityDateLbl {
            get {
                return ResourceManager.GetString("ValidityDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Rate.
        /// </summary>
        internal static string VATRateLbl {
            get {
                return ResourceManager.GetString("VATRateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Analysis Report.
        /// </summary>
        internal static string VehiclePerformanceReportIndLbl {
            get {
                return ResourceManager.GetString("VehiclePerformanceReportIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Register No.
        /// </summary>
        internal static string VehRegsNoLbl {
            get {
                return ResourceManager.GetString("VehRegsNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Password.
        /// </summary>
        internal static string WebPasswordLbl {
            get {
                return ResourceManager.GetString("WebPasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web User Id.
        /// </summary>
        internal static string WebUserIdLbl {
            get {
                return ResourceManager.GetString("WebUserIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withheld Unsettle Id.
        /// </summary>
        internal static string WithHeldUnsettleIdLbl {
            get {
                return ResourceManager.GetString("WithHeldUnsettleIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding Tax Indicator.
        /// </summary>
        internal static string WithholdingTaxIndLbl {
            get {
                return ResourceManager.GetString("WithholdingTaxIndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writeoff Date.
        /// </summary>
        internal static string WriteoffDateLbl {
            get {
                return ResourceManager.GetString("WriteoffDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xreference Doc.
        /// </summary>
        internal static string XreferenceDocLbl {
            get {
                return ResourceManager.GetString("XreferenceDocLbl", resourceCulture);
            }
        }
    }
}
