//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelSector.Global_Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class locale_home_index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_home_index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelSector.Global_Resources.Home.locale_home_index", typeof(locale_home_index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string accordion_admin {
            get {
                return ResourceManager.GetString("accordion_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string accordion_help {
            get {
                return ResourceManager.GetString("accordion_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Operations.
        /// </summary>
        public static string accordion_loyaltyops {
            get {
                return ResourceManager.GetString("accordion_loyaltyops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string accordion_operations {
            get {
                return ResourceManager.GetString("accordion_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string accordion_tools {
            get {
                return ResourceManager.GetString("accordion_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string acordion_security {
            get {
                return ResourceManager.GetString("acordion_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Logo.
        /// </summary>
        public static string cardlogo {
            get {
                return ResourceManager.GetString("cardlogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        public static string cardtype {
            get {
                return ResourceManager.GetString("cardtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2012 Cardtrend Systems Sdn Bhd. All Rights Reserved®.
        /// </summary>
        public static string copyrightmsg {
            get {
                return ResourceManager.GetString("copyrightmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATE.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost Card/Virtual Card Batch Generation.
        /// </summary>
        public static string Ghostcard {
            get {
                return ResourceManager.GetString("Ghostcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost Card/Virtual Card Batch Generation.
        /// </summary>
        public static string ghostcardtitle {
            get {
                return ResourceManager.GetString("ghostcardtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Panel.
        /// </summary>
        public static string hidepanel {
            get {
                return ResourceManager.GetString("hidepanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string loggedinas {
            get {
                return ResourceManager.GetString("loggedinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Account Agreement.
        /// </summary>
        public static string MerchantAccount {
            get {
                return ResourceManager.GetString("MerchantAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Account List.
        /// </summary>
        public static string Merchantaccountlist {
            get {
                return ResourceManager.GetString("Merchantaccountlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Terminal Device.
        /// </summary>
        public static string Merchantterminaldevice {
            get {
                return ResourceManager.GetString("Merchantterminaldevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Accounts.
        /// </summary>
        public static string noofaccounts {
            get {
                return ResourceManager.GetString("noofaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Cards.
        /// </summary>
        public static string noofcards {
            get {
                return ResourceManager.GetString("noofcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Type.
        /// </summary>
        public static string plastictype {
            get {
                return ResourceManager.GetString("plastictype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string security1 {
            get {
                return ResourceManager.GetString("security1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOut.
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Promo.
        /// </summary>
        public static string Specialpromo {
            get {
                return ResourceManager.GetString("Specialpromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unposted Transaction Search.
        /// </summary>
        public static string Unpostedtransaction {
            get {
                return ResourceManager.GetString("Unpostedtransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsettle Transaction Search.
        /// </summary>
        public static string Unsettletransaction {
            get {
                return ResourceManager.GetString("Unsettletransaction", resourceCulture);
            }
        }
    }
}
