//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrend.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardTrend.Common.Resources.IssMessages", typeof(IssMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been updated successfully.
        /// </summary>
        public static string Msg50091 {
            get {
                return ResourceManager.GetString("Msg50091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been created successfully.
        /// </summary>
        public static string Msg50168 {
            get {
                return ResourceManager.GetString("Msg50168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been updated successfully.
        /// </summary>
        public static string Msg50169 {
            get {
                return ResourceManager.GetString("Msg50169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process successfully completed.
        /// </summary>
        public static string Msg54143 {
            get {
                return ResourceManager.GetString("Msg54143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Type is a compulsory field.
        /// </summary>
        public static string Msg55003 {
            get {
                return ResourceManager.GetString("Msg55003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Method  is a compulsory field.
        /// </summary>
        public static string Msg55020 {
            get {
                return ResourceManager.GetString("Msg55020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID is a compulsory field.
        /// </summary>
        public static string Msg55033 {
            get {
                return ResourceManager.GetString("Msg55033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority is a compulsory field.
        /// </summary>
        public static string Msg55081 {
            get {
                return ResourceManager.GetString("Msg55081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name is a compulsory field.
        /// </summary>
        public static string Msg55084 {
            get {
                return ResourceManager.GetString("Msg55084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership is a compulsory field.
        /// </summary>
        public static string Msg55114 {
            get {
                return ResourceManager.GetString("Msg55114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode is a compulsory field.
        /// </summary>
        public static string Msg55163 {
            get {
                return ResourceManager.GetString("Msg55163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Type is a compulsory field.
        /// </summary>
        public static string Msg55164 {
            get {
                return ResourceManager.GetString("Msg55164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Type is a compulsory field.
        /// </summary>
        public static string Msg55313 {
            get {
                return ResourceManager.GetString("Msg55313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Amount is a compulsory field.
        /// </summary>
        public static string Msg55314 {
            get {
                return ResourceManager.GetString("Msg55314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string Msg60000 {
            get {
                return ResourceManager.GetString("Msg60000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Type not found.
        /// </summary>
        public static string Msg60013 {
            get {
                return ResourceManager.GetString("Msg60013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        public static string Msg60031 {
            get {
                return ResourceManager.GetString("Msg60031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Application Id (same company registered number) already exists.
        /// </summary>
        public static string Msg65065 {
            get {
                return ResourceManager.GetString("Msg65065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Reference already exists.
        /// </summary>
        public static string Msg65118 {
            get {
                return ResourceManager.GetString("Msg65118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert Contact Number.
        /// </summary>
        public static string Msg70084 {
            get {
                return ResourceManager.GetString("Msg70084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Entity.
        /// </summary>
        public static string Msg70110 {
            get {
                return ResourceManager.GetString("Msg70110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Account.
        /// </summary>
        public static string Msg70124 {
            get {
                return ResourceManager.GetString("Msg70124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Contact Number.
        /// </summary>
        public static string Msg70146 {
            get {
                return ResourceManager.GetString("Msg70146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update application.
        /// </summary>
        public static string Msg70188 {
            get {
                return ResourceManager.GetString("Msg70188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert into temporary table.
        /// </summary>
        public static string Msg70271 {
            get {
                return ResourceManager.GetString("Msg70271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Bank Account.
        /// </summary>
        public static string Msg70436 {
            get {
                return ResourceManager.GetString("Msg70436", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create next milestone.
        /// </summary>
        public static string Msg71153 {
            get {
                return ResourceManager.GetString("Msg71153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check on override status &amp; expiry date.
        /// </summary>
        public static string Msg95405 {
            get {
                return ResourceManager.GetString("Msg95405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit limit for postpaid account only.
        /// </summary>
        public static string Msg95408 {
            get {
                return ResourceManager.GetString("Msg95408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company embossing name is required.
        /// </summary>
        public static string Msg95409 {
            get {
                return ResourceManager.GetString("Msg95409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of Embossing Name exceeded 26 characters.
        /// </summary>
        public static string Msg95591 {
            get {
                return ResourceManager.GetString("Msg95591", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status.
        /// </summary>
        public static string Msg95596 {
            get {
                return ResourceManager.GetString("Msg95596", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is not allowed due to bad account status.
        /// </summary>
        public static string Msg95614 {
            get {
                return ResourceManager.GetString("Msg95614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is either Billing or Delivery address does not exists.
        /// </summary>
        public static string Msg95619 {
            get {
                return ResourceManager.GetString("Msg95619", resourceCulture);
            }
        }
    }
}
