//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrend.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardTrend.Common.Resources.LoginMessages", typeof(LoginMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account not found.
        /// </summary>
        internal static string Msg60004 {
            get {
                return ResourceManager.GetString("Msg60004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call system administrator for help.
        /// </summary>
        internal static string Msg70922 {
            get {
                return ResourceManager.GetString("Msg70922", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update user profile.
        /// </summary>
        internal static string Msg70923 {
            get {
                return ResourceManager.GetString("Msg70923", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been disabled.
        /// </summary>
        internal static string Msg95008 {
            get {
                return ResourceManager.GetString("Msg95008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string Msg95184 {
            get {
                return ResourceManager.GetString("Msg95184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password exceeds 90 days.
        /// </summary>
        internal static string Msg95670 {
            get {
                return ResourceManager.GetString("Msg95670", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change your password Upon first logon.
        /// </summary>
        internal static string Msg95674 {
            get {
                return ResourceManager.GetString("Msg95674", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string MsgLoginError {
            get {
                return ResourceManager.GetString("MsgLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string MsgLoginSuccess {
            get {
                return ResourceManager.GetString("MsgLoginSuccess", resourceCulture);
            }
        }
    }
}
