//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelSector.Global_Resources.Operations.MerchAgreement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class locale_operations_merchagrmnt_index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_operations_merchagrmnt_index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelSector.Global_Resources.Operations.MerchAgreement.locale_operations_merchagr" +
                            "mnt_index", typeof(locale_operations_merchagrmnt_index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement By AccountNo.
        /// </summary>
        public static string agrmentbyAcctno {
            get {
                return ResourceManager.GetString("agrmentbyAcctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement By Merchant.
        /// </summary>
        public static string agrmentbyMerchant {
            get {
                return ResourceManager.GetString("agrmentbyMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By AccountNo.
        /// </summary>
        public static string byacctno {
            get {
                return ResourceManager.GetString("byacctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Merchant.
        /// </summary>
        public static string bymerchant {
            get {
                return ResourceManager.GetString("bymerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Location.
        /// </summary>
        public static string grdBusnlocation {
            get {
                return ResourceManager.GetString("grdBusnlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name.
        /// </summary>
        public static string grdBusnName {
            get {
                return ResourceManager.GetString("grdBusnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string grdcreatedby {
            get {
                return ResourceManager.GetString("grdcreatedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string grdcreationDate {
            get {
                return ResourceManager.GetString("grdcreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string grdstatus {
            get {
                return ResourceManager.GetString("grdstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        public static string grgAcctNo {
            get {
                return ResourceManager.GetString("grgAcctNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Agreement.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
