//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelSector.Global_Resources.Operations.MerchAgreement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class locale_operations_merchagrmnt_new {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_operations_merchagrmnt_new() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelSector.Global_Resources.Operations.MerchAgreement.locale_operations_merchagr" +
                            "mnt_new", typeof(locale_operations_merchagrmnt_new).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string acctname {
            get {
                return ResourceManager.GetString("acctname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address List.
        /// </summary>
        public static string addresslist {
            get {
                return ResourceManager.GetString("addresslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        public static string addresstype {
            get {
                return ResourceManager.GetString("addresstype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Date.
        /// </summary>
        public static string agrmntdate {
            get {
                return ResourceManager.GetString("agrmntdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account No.
        /// </summary>
        public static string bankacctno {
            get {
                return ResourceManager.GetString("bankacctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string bankname {
            get {
                return ResourceManager.GetString("bankname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        public static string bloodgroup {
            get {
                return ResourceManager.GetString("bloodgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string cntrycd {
            get {
                return ResourceManager.GetString("cntrycd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string contactname {
            get {
                return ResourceManager.GetString("contactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts List.
        /// </summary>
        public static string contactslist {
            get {
                return ResourceManager.GetString("contactslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string contacttype {
            get {
                return ResourceManager.GetString("contacttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoRegs No.
        /// </summary>
        public static string coregsno {
            get {
                return ResourceManager.GetString("coregsno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Code.
        /// </summary>
        public static string corporatecode {
            get {
                return ResourceManager.GetString("corporatecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string createdby {
            get {
                return ResourceManager.GetString("createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string creationdate {
            get {
                return ResourceManager.GetString("creationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string dob {
            get {
                return ResourceManager.GetString("dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        public static string emailid {
            get {
                return ResourceManager.GetString("emailid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Detail.
        /// </summary>
        public static string employmentdtl {
            get {
                return ResourceManager.GetString("employmentdtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Wizard.
        /// </summary>
        public static string enablewizard {
            get {
                return ResourceManager.GetString("enablewizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string entity_title {
            get {
                return ResourceManager.GetString("entity_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity ID.
        /// </summary>
        public static string entityid {
            get {
                return ResourceManager.GetString("entityid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment.
        /// </summary>
        public static string establishment {
            get {
                return ResourceManager.GetString("establishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string income {
            get {
                return ResourceManager.GetString("income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string maritalstatus {
            get {
                return ResourceManager.GetString("maritalstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCC.
        /// </summary>
        public static string mcc {
            get {
                return ResourceManager.GetString("mcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New IC.
        /// </summary>
        public static string newic {
            get {
                return ResourceManager.GetString("newic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Merchant.
        /// </summary>
        public static string newmerchant {
            get {
                return ResourceManager.GetString("newmerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string occupation {
            get {
                return ResourceManager.GetString("occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old IC.
        /// </summary>
        public static string oldic {
            get {
                return ResourceManager.GetString("oldic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        public static string ownership {
            get {
                return ResourceManager.GetString("ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No.
        /// </summary>
        public static string passportno {
            get {
                return ResourceManager.GetString("passportno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal banking Details.
        /// </summary>
        public static string personalbankingdtls {
            get {
                return ResourceManager.GetString("personalbankingdtls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Particulars.
        /// </summary>
        public static string personalparticulars {
            get {
                return ResourceManager.GetString("personalparticulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person in Charge.
        /// </summary>
        public static string personincharge {
            get {
                return ResourceManager.GetString("personincharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string pincd {
            get {
                return ResourceManager.GetString("pincd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        public static string reasoncd {
            get {
                return ResourceManager.GetString("reasoncd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Name.
        /// </summary>
        public static string registeredname {
            get {
                return ResourceManager.GetString("registeredname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIC.
        /// </summary>
        public static string sic {
            get {
                return ResourceManager.GetString("sic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 1.
        /// </summary>
        public static string street1 {
            get {
                return ResourceManager.GetString("street1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street 2.
        /// </summary>
        public static string street2 {
            get {
                return ResourceManager.GetString("street2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 3.
        /// </summary>
        public static string street3 {
            get {
                return ResourceManager.GetString("street3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string tabaddress {
            get {
                return ResourceManager.GetString("tabaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string tabcontacts {
            get {
                return ResourceManager.GetString("tabcontacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string tabdetail {
            get {
                return ResourceManager.GetString("tabdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string tabentity {
            get {
                return ResourceManager.GetString("tabentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string tabreview {
            get {
                return ResourceManager.GetString("tabreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        public static string taxid {
            get {
                return ResourceManager.GetString("taxid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Info.
        /// </summary>
        public static string taxinfo {
            get {
                return ResourceManager.GetString("taxinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
    }
}
