//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelSector.Global_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelSector.Global_Resources.locale", typeof(locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string accordion_admin {
            get {
                return ResourceManager.GetString("accordion_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string accordion_help {
            get {
                return ResourceManager.GetString("accordion_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Operations.
        /// </summary>
        public static string accordion_loyaltyops {
            get {
                return ResourceManager.GetString("accordion_loyaltyops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string accordion_operations {
            get {
                return ResourceManager.GetString("accordion_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string accordion_tools {
            get {
                return ResourceManager.GetString("accordion_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        public static string accountno {
            get {
                return ResourceManager.GetString("accountno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        public static string accountnumber {
            get {
                return ResourceManager.GetString("accountnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string acctname {
            get {
                return ResourceManager.GetString("acctname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address List.
        /// </summary>
        public static string addresslist {
            get {
                return ResourceManager.GetString("addresslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        public static string addresstype {
            get {
                return ResourceManager.GetString("addresstype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aging No.
        /// </summary>
        public static string agingno {
            get {
                return ResourceManager.GetString("agingno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement By AccountNo.
        /// </summary>
        public static string agrmentbyacctno {
            get {
                return ResourceManager.GetString("agrmentbyacctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement By Merchant.
        /// </summary>
        public static string agrmentbyMerchant {
            get {
                return ResourceManager.GetString("agrmentbyMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Date.
        /// </summary>
        public static string agrmntdate {
            get {
                return ResourceManager.GetString("agrmntdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Id.
        /// </summary>
        public static string applicationid {
            get {
                return ResourceManager.GetString("applicationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code.
        /// </summary>
        public static string approvalcode {
            get {
                return ResourceManager.GetString("approvalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array.
        /// </summary>
        public static string array {
            get {
                return ResourceManager.GetString("array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Date.
        /// </summary>
        public static string assigndate {
            get {
                return ResourceManager.GetString("assigndate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Log Tracking.
        /// </summary>
        public static string auditlogtracking {
            get {
                return ResourceManager.GetString("auditlogtracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Card Expiry.
        /// </summary>
        public static string authorizationcardexpiry {
            get {
                return ResourceManager.GetString("authorizationcardexpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Card No.
        /// </summary>
        public static string authorizationcardno {
            get {
                return ResourceManager.GetString("authorizationcardno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account No.
        /// </summary>
        public static string bankacctno {
            get {
                return ResourceManager.GetString("bankacctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Type.
        /// </summary>
        public static string bankaccttype {
            get {
                return ResourceManager.GetString("bankaccttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string bankname {
            get {
                return ResourceManager.GetString("bankname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch ID.
        /// </summary>
        public static string batchid {
            get {
                return ResourceManager.GetString("batchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        public static string batchno {
            get {
                return ResourceManager.GetString("batchno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        public static string bloodgroup {
            get {
                return ResourceManager.GetString("bloodgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string busnname {
            get {
                return ResourceManager.GetString("busnname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By AccountNo.
        /// </summary>
        public static string byaccountno {
            get {
                return ResourceManager.GetString("byaccountno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Merchant No.
        /// </summary>
        public static string bymerchant {
            get {
                return ResourceManager.GetString("bymerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card &amp; Account Maintanance.
        /// </summary>
        public static string camaintnoverview {
            get {
                return ResourceManager.GetString("camaintnoverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Courier and Collection.
        /// </summary>
        public static string cardcourierncoll {
            get {
                return ResourceManager.GetString("cardcourierncoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Expiry.
        /// </summary>
        public static string cardexpiry {
            get {
                return ResourceManager.GetString("cardexpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Logo.
        /// </summary>
        public static string cardlogo {
            get {
                return ResourceManager.GetString("cardlogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        public static string cardno {
            get {
                return ResourceManager.GetString("cardno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Replacement.
        /// </summary>
        public static string cardreplacement {
            get {
                return ResourceManager.GetString("cardreplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        public static string cardtype {
            get {
                return ResourceManager.GetString("cardtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card &amp; Account Signup.
        /// </summary>
        public static string casignup {
            get {
                return ResourceManager.GetString("casignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Status.
        /// </summary>
        public static string changetostatus {
            get {
                return ResourceManager.GetString("changetostatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChequeNo.
        /// </summary>
        public static string chequeno {
            get {
                return ResourceManager.GetString("chequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection ID.
        /// </summary>
        public static string collectionid {
            get {
                return ResourceManager.GetString("collectionid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector ID.
        /// </summary>
        public static string collectorid {
            get {
                return ResourceManager.GetString("collectorid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Legal Name.
        /// </summary>
        public static string companylegalname {
            get {
                return ResourceManager.GetString("companylegalname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration Date.
        /// </summary>
        public static string companyregistrationdate {
            get {
                return ResourceManager.GetString("companyregistrationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration Name.
        /// </summary>
        public static string companyregistrationname {
            get {
                return ResourceManager.GetString("companyregistrationname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration No.
        /// </summary>
        public static string companyregistrationnumber {
            get {
                return ResourceManager.GetString("companyregistrationnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        public static string companytype {
            get {
                return ResourceManager.GetString("companytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string contactname {
            get {
                return ResourceManager.GetString("contactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        public static string contactno {
            get {
                return ResourceManager.GetString("contactno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts List.
        /// </summary>
        public static string contactslist {
            get {
                return ResourceManager.GetString("contactslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string contacttype {
            get {
                return ResourceManager.GetString("contacttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2012 Cardtrend Systems Sdn Bhd..
        /// </summary>
        public static string copyrightmsg {
            get {
                return ResourceManager.GetString("copyrightmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Code.
        /// </summary>
        public static string corporatecode {
            get {
                return ResourceManager.GetString("corporatecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Name.
        /// </summary>
        public static string corporatename {
            get {
                return ResourceManager.GetString("corporatename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Consignment Note.
        /// </summary>
        public static string courierconsignmentnote {
            get {
                return ResourceManager.GetString("courierconsignmentnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string createdby {
            get {
                return ResourceManager.GetString("createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string creationdate {
            get {
                return ResourceManager.GetString("creationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string ctrycd {
            get {
                return ResourceManager.GetString("ctrycd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string currentstatus {
            get {
                return ResourceManager.GetString("currentstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Date.
        /// </summary>
        public static string cycledate {
            get {
                return ResourceManager.GetString("cycledate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle No.
        /// </summary>
        public static string cyclenumber {
            get {
                return ResourceManager.GetString("cyclenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts Collection.
        /// </summary>
        public static string debtscollection {
            get {
                return ResourceManager.GetString("debtscollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered By.
        /// </summary>
        public static string deliveredby {
            get {
                return ResourceManager.GetString("deliveredby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method.
        /// </summary>
        public static string deliverymethod {
            get {
                return ResourceManager.GetString("deliverymethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Status.
        /// </summary>
        public static string deliverystatus {
            get {
                return ResourceManager.GetString("deliverystatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string descp {
            get {
                return ResourceManager.GetString("descp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string dob {
            get {
                return ResourceManager.GetString("dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adress.
        /// </summary>
        public static string emailaddr {
            get {
                return ResourceManager.GetString("emailaddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Detail.
        /// </summary>
        public static string employmentdtl {
            get {
                return ResourceManager.GetString("employmentdtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Wizard.
        /// </summary>
        public static string enablewizard {
            get {
                return ResourceManager.GetString("enablewizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsed By.
        /// </summary>
        public static string endorsedby {
            get {
                return ResourceManager.GetString("endorsedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsed Date.
        /// </summary>
        public static string endorseddate {
            get {
                return ResourceManager.GetString("endorseddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string entity_title {
            get {
                return ResourceManager.GetString("entity_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity ID.
        /// </summary>
        public static string entityid {
            get {
                return ResourceManager.GetString("entityid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment.
        /// </summary>
        public static string establishment {
            get {
                return ResourceManager.GetString("establishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Logger.
        /// </summary>
        public static string eventlogger {
            get {
                return ResourceManager.GetString("eventlogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Code.
        /// </summary>
        public static string feecd {
            get {
                return ResourceManager.GetString("feecd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost Card/Virtual Card Batch Generation.
        /// </summary>
        public static string ghostcardtitle {
            get {
                return ResourceManager.GetString("ghostcardtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string grdcreationDate {
            get {
                return ResourceManager.GetString("grdcreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string grdstatus {
            get {
                return ResourceManager.GetString("grdstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        public static string grgacctno {
            get {
                return ResourceManager.GetString("grgacctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Panel.
        /// </summary>
        public static string hidepanel {
            get {
                return ResourceManager.GetString("hidepanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string income {
            get {
                return ResourceManager.GetString("income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string invoicenumber {
            get {
                return ResourceManager.GetString("invoicenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        public static string lastupdatedate {
            get {
                return ResourceManager.GetString("lastupdatedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string loggedinas {
            get {
                return ResourceManager.GetString("loggedinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Slip Entry.
        /// </summary>
        public static string manualslipentry {
            get {
                return ResourceManager.GetString("manualslipentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string maritalstatus {
            get {
                return ResourceManager.GetString("maritalstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCC.
        /// </summary>
        public static string mcc {
            get {
                return ResourceManager.GetString("mcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Account Signup.
        /// </summary>
        public static string merchagreementindextitle {
            get {
                return ResourceManager.GetString("merchagreementindextitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account Signup.
        /// </summary>
        public static string merchagreementnewtitle {
            get {
                return ResourceManager.GetString("merchagreementnewtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Account Signup.
        /// </summary>
        public static string MerchantAccount {
            get {
                return ResourceManager.GetString("MerchantAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Account List.
        /// </summary>
        public static string Merchantaccountlist {
            get {
                return ResourceManager.GetString("Merchantaccountlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Agreement SignUp.
        /// </summary>
        public static string merchantagreementsignup {
            get {
                return ResourceManager.GetString("merchantagreementsignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Terminal Device.
        /// </summary>
        public static string Merchantterminaldevice {
            get {
                return ResourceManager.GetString("Merchantterminaldevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant No.
        /// </summary>
        public static string merchno {
            get {
                return ResourceManager.GetString("merchno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of Business.
        /// </summary>
        public static string natureofbusiness {
            get {
                return ResourceManager.GetString("natureofbusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card Expiry Date.
        /// </summary>
        public static string newcardexpirydate {
            get {
                return ResourceManager.GetString("newcardexpirydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New IC.
        /// </summary>
        public static string newic {
            get {
                return ResourceManager.GetString("newic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Merchant.
        /// </summary>
        public static string newmerchant {
            get {
                return ResourceManager.GetString("newmerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Accounts.
        /// </summary>
        public static string noofaccounts {
            get {
                return ResourceManager.GetString("noofaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Cards.
        /// </summary>
        public static string noofcards {
            get {
                return ResourceManager.GetString("noofcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string occupation {
            get {
                return ResourceManager.GetString("occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Reading.
        /// </summary>
        public static string odometerreading {
            get {
                return ResourceManager.GetString("odometerreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old IC.
        /// </summary>
        public static string oldic {
            get {
                return ResourceManager.GetString("oldic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        public static string ownership {
            get {
                return ResourceManager.GetString("ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No.
        /// </summary>
        public static string passportno {
            get {
                return ResourceManager.GetString("passportno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal banking Details.
        /// </summary>
        public static string personalbankingdtls {
            get {
                return ResourceManager.GetString("personalbankingdtls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Particulars.
        /// </summary>
        public static string personalparticulars {
            get {
                return ResourceManager.GetString("personalparticulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person in Charge.
        /// </summary>
        public static string personincharge {
            get {
                return ResourceManager.GetString("personincharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string pincd {
            get {
                return ResourceManager.GetString("pincd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Generation.
        /// </summary>
        public static string pingeneration {
            get {
                return ResourceManager.GetString("pingeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Mailing Type.
        /// </summary>
        public static string pinmailingtype {
            get {
                return ResourceManager.GetString("pinmailingtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Type.
        /// </summary>
        public static string plastictype {
            get {
                return ResourceManager.GetString("plastictype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string postalcode {
            get {
                return ResourceManager.GetString("postalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string productcode {
            get {
                return ResourceManager.GetString("productcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        public static string reasoncd {
            get {
                return ResourceManager.GetString("reasoncd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        public static string reasoncode {
            get {
                return ResourceManager.GetString("reasoncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassigned Collector ID.
        /// </summary>
        public static string reassignedcollectorid {
            get {
                return ResourceManager.GetString("reassignedcollectorid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassigned Date.
        /// </summary>
        public static string reassigneddate {
            get {
                return ResourceManager.GetString("reassigneddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt No.
        /// </summary>
        public static string receiptno {
            get {
                return ResourceManager.GetString("receiptno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved Date.
        /// </summary>
        public static string recieveddate {
            get {
                return ResourceManager.GetString("recieveddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Name.
        /// </summary>
        public static string recipientname {
            get {
                return ResourceManager.GetString("recipientname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        public static string referenceid {
            get {
                return ResourceManager.GetString("referenceid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type.
        /// </summary>
        public static string referencetype {
            get {
                return ResourceManager.GetString("referencetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Name.
        /// </summary>
        public static string registeredname {
            get {
                return ResourceManager.GetString("registeredname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Viewer.
        /// </summary>
        public static string reportviewer {
            get {
                return ResourceManager.GetString("reportviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval Reference No.
        /// </summary>
        public static string retrivalreferencenumber {
            get {
                return ResourceManager.GetString("retrivalreferencenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search cardno,account no,name,ic,card address etc..
        /// </summary>
        public static string searchbox_text {
            get {
                return ResourceManager.GetString("searchbox_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string security1 {
            get {
                return ResourceManager.GetString("security1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence No.
        /// </summary>
        public static string sequenceno {
            get {
                return ResourceManager.GetString("sequenceno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettledDate.
        /// </summary>
        public static string settleddate {
            get {
                return ResourceManager.GetString("settleddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string shortname {
            get {
                return ResourceManager.GetString("shortname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIC.
        /// </summary>
        public static string sic {
            get {
                return ResourceManager.GetString("sic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOut.
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Promo.
        /// </summary>
        public static string Specialpromo {
            get {
                return ResourceManager.GetString("Specialpromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan.
        /// </summary>
        public static string stan {
            get {
                return ResourceManager.GetString("stan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Type.
        /// </summary>
        public static string statementtype {
            get {
                return ResourceManager.GetString("statementtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Maintanance.
        /// </summary>
        public static string statusMaintanance {
            get {
                return ResourceManager.GetString("statusMaintanance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 1.
        /// </summary>
        public static string street1 {
            get {
                return ResourceManager.GetString("street1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street 2.
        /// </summary>
        public static string street2 {
            get {
                return ResourceManager.GetString("street2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 3.
        /// </summary>
        public static string street3 {
            get {
                return ResourceManager.GetString("street3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string tabaddress {
            get {
                return ResourceManager.GetString("tabaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string tabcontact {
            get {
                return ResourceManager.GetString("tabcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string tabdetail {
            get {
                return ResourceManager.GetString("tabdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string tabentity {
            get {
                return ResourceManager.GetString("tabentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string tabreview {
            get {
                return ResourceManager.GetString("tabreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task No.
        /// </summary>
        public static string taskno {
            get {
                return ResourceManager.GetString("taskno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        public static string taxid {
            get {
                return ResourceManager.GetString("taxid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Info.
        /// </summary>
        public static string taxinfo {
            get {
                return ResourceManager.GetString("taxinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Id.
        /// </summary>
        public static string terminalid {
            get {
                return ResourceManager.GetString("terminalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Inventory.
        /// </summary>
        public static string termInventory {
            get {
                return ResourceManager.GetString("termInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string totalamount {
            get {
                return ResourceManager.GetString("totalamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        public static string totalcount {
            get {
                return ResourceManager.GetString("totalcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points.
        /// </summary>
        public static string totalpoints {
            get {
                return ResourceManager.GetString("totalpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Quantity.
        /// </summary>
        public static string totalquantity {
            get {
                return ResourceManager.GetString("totalquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Adjustment.
        /// </summary>
        public static string transactionadjustment {
            get {
                return ResourceManager.GetString("transactionadjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code.
        /// </summary>
        public static string transactioncode {
            get {
                return ResourceManager.GetString("transactioncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string transactiondate {
            get {
                return ResourceManager.GetString("transactiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string transactionid {
            get {
                return ResourceManager.GetString("transactionid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Amount.
        /// </summary>
        public static string txnAmnt {
            get {
                return ResourceManager.GetString("txnAmnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code.
        /// </summary>
        public static string txncd {
            get {
                return ResourceManager.GetString("txncd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string unitprice {
            get {
                return ResourceManager.GetString("unitprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsettle Transaction Search.
        /// </summary>
        public static string unsettletxn {
            get {
                return ResourceManager.GetString("unsettletxn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unposted Transaction Search.
        /// </summary>
        public static string uppostedtxn {
            get {
                return ResourceManager.GetString("uppostedtxn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string userid {
            get {
                return ResourceManager.GetString("userid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Performance Report.
        /// </summary>
        public static string vehicleperformancereport {
            get {
                return ResourceManager.GetString("vehicleperformancereport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Type.
        /// </summary>
        public static string velocitytype {
            get {
                return ResourceManager.GetString("velocitytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XReference Id.
        /// </summary>
        public static string xreferenceid {
            get {
                return ResourceManager.GetString("xreferenceid", resourceCulture);
            }
        }
    }
}
